#!/bin/sh
#
# mysql-proxy This script starts and stops the mysql-proxy daemon
#
# chkconfig: - 78 30
# processname: mysql-proxy
# description: mysql-proxy is a proxy daemon for mysql

# Source function library.

. %(QSERV_DIR)s/etc/init.d/qserv-functions

prog="mysql-proxy"

# Source networking configuration.
if [ -f /etc/sysconfig/network ]; then
    . /etc/sysconfig/network
fi

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

# Set default mysql-proxy configuration.
PROXY_OPTIONS="--daemon"
pidfile=%(QSERV_DIR)s/var/run/mysql-proxy.pid
PROXY_CONFIG=%(QSERV_DIR)s/etc/my-proxy.cnf
lockfile=%(QSERV_DIR)s/var/lock/subsys/$prog
stoptimeout=1

LUA_DEBUG_LEVEL=0
LUA_LOG_FILE=%(QSERV_LOG_DIR)s/mysql-proxy-lua.log
QSERV_MASTER_PORT=%(QSERV_RPC_PORT)s

BINARY=%(QSERV_DIR)s/bin/$prog

# Source mysql-proxy configuration.
if [ -f %(QSERV_DIR)s/etc/sysconfig/mysql-proxy ]; then
    . %(QSERV_DIR)s/etc/sysconfig/mysql-proxy
fi

# WARNING : can only use the --user switch if running as root
proxy_user_option=""
if [ "$USER" = "root" ]; then
    proxy_user=%(QSERV_UNIX_USER)s
    proxy_user_option="--user=$proxy_user"
fi

cmd="DEBUG=${LUA_DEBUG_LEVEL} QSERV_RPC_PORT=${QSERV_MASTER_PORT} ${BINARY} $PROXY_OPTIONS --pid-file=$pidfile $proxy_user_option --defaults-file=${PROXY_CONFIG} &> ${LUA_LOG_FILE}"


start_cmd() {
    start -p $pidfile -l $lockfile $prog "${cmd}"
}

stop_cmd() {
    stop -p $pidfile -l $lockfile -t ${stoptimeout} $prog
}

# See how we were called.
case "$1" in
    start)
        start_cmd
        ;;
    stop)
        stop_cmd
        ;;
    restart)
        stop_cmd
        start_cmd
        ;;
    condrestart|try-restart)
        if status -p $pidfile $prog >&/dev/null; then
            stop_cmd
            start_cmd
        fi
        ;;
    status)
        status -p $pidfile $prog
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status|condrestart|try-restart}"
        exit 2
        ;;
esac

exit $?

