#!/bin/sh
#
# qms		This shell script takes care of starting and stopping
#		qms (Qserv Meta Service).
#
# description: qms is the Qserv Meta Service. \
# It is used by Qserv master in order to get accurate informations \
# about loaded dataset. \
# Note that Qserv service won't start if QMS databse is empty.

### BEGIN INIT INFO
# Provides: qms
# Short-Description: start and stop qms
# Description: qms is the Qserv Meta Service. It is used by Qserv master
#              in order to get accurate informations about loaded datasets.
#              Note that Qserv service won't start if QMS databse is empty.
### END INIT INFO

. ${QSERV_DIR}/etc/init.d/qserv-functions

PATH=%(PATH)s
QSERV_DIR=%(QSERV_DIR)s
QSERV_RUN_DIR=%(QSERV_RUN_DIR)s
QSERV_PID_DIR=%(QSERV_PID_DIR)s
QSERV_LOG_DIR=%(QSERV_LOG_DIR)s

SERVICE_NAME="Qserv Metadata Server (QMS)"

NAME="qms"
DAEMON=${NAME}

export PATH

START=${QSERV_DIR}/bin/startQMS.py
CONFIG=${QSERV_DIR}/etc/qms.cnf
pidfile=${QSERV_PID_DIR}/${NAME}.pid
lockfile=${QSERV_DIR}/var/lock/subsys/${NAME}
LOGFILE=${QSERV_LOG_DIR}/${NAME}-startup.log
starttimeout=1

cmd="${PYTHON} ${START} -c ${CONFIG} > ${LOGFILE} 2>&1 &"

start_cmd() {
    start -p $pidfile -l $lockfile -t ${starttimeout} $NAME "${cmd}"
}

stop_cmd() {
    stop -p $pidfile -l $lockfile $NAME
}

# See how we were called.
case "$1" in
    start)
        start_cmd
        ;;
    stop)
        stop_cmd
        ;;
    restart)
        stop_cmd
        start_cmd
        ;;
    condrestart|try-restart)
        if status_of_proc -p $pidfile "$DAEMON" "$NAME" >&/dev/null; then
            stop_cmd
            start_cmd
        fi
        ;;
    status)
	status_of_proc -p $pidfile "$DAEMON" "$NAME"	
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status|condrestart|try-restart}"
        exit 2
        ;;
esac

exit $?
