#!/bin/sh
#
# qserv-master  This shell script takes care of starting and stopping
#	        Qserv master.
#
# description: qserv-master is the Qserv master service \
# It receive SQL queries process it and send it to Qserv workers \
# and then it returns the results it to mysql-proxy. \
# Note that Qserv service won't start if QMS database is empty.

### BEGIN INIT INFO
# Provides: qserv-master
# Short-Description: start and stop qserv master
# Description: qserv-master is the Qserv master service \
#              It receive SQL queries process it and send it to Qserv workers \
#              and then it returns the results it to mysql-proxy. \
#              Note that Qserv service won't start if QMS database is empty.
### END INIT INFO

. %(QSERV_DIR)s/etc/init.d/qserv-functions

prog="qserv-master"

START=startQserv.py
CONFIG=%(QSERV_DIR)s/etc/local.qserv.cnf
pidfile=%(QSERV_PID_DIR)s/${prog}.pid
lockfile=%(QSERV_RUN_DIR)s/var/lock/subsys/${prog}
LOGFILE=%(QSERV_LOG_DIR)s/${prog}.log
starttimeout=1

export PATH=%(PATH)s
export PYTHONPATH=%(PYTHONPATH)s

export QSW_RESULTDIR=%(QSERV_RUN_DIR)s/qserv-run/tmp
# Disabling buffering in python in order to enable "real-time" logging.
export PYTHONUNBUFFERED=1

cmd="${PYTHON} ${START} -c ${CONFIG} &> ${LOGFILE} &"

start_cmd() {
    start -p $pidfile -l $lockfile -t ${starttimeout} $prog "${cmd}"
}

stop_cmd() {
    stop -p $pidfile -l $lockfile $prog
}

# See how we were called.
case "$1" in
    start)
        start_cmd
        ;;
    stop)
        stop_cmd
        ;;
    restart)
        stop_cmd
        start_cmd
        ;;
    condrestart|try-restart)
        if status -p $pidfile $prog >&/dev/null; then
            stop_cmd
            start_cmd
        fi
        ;;
    status)
        status -p $pidfile $prog
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status|condrestart|try-restart}"
        exit 2
        ;;
esac

exit $?
