# -*- python -*-
Import('env')
Import('envNoXrd')

pathSrcs = ["nulltool.cc", 
            envNoXrd.Object(target="QservPathStructure.o", 
                            source="../src/QservPathStructure.cc")]
envNoXrd.Program("nulltool", pathSrcs)
