# -*- python -*-
Import('env')
Import('envNoXrd')
Import('detect_deps')
import os

pEnv = envNoXrd.Clone()
pEnv.Append(CPPPATH=envNoXrd["built_cpppath"])
pEnv.Append(LIBPATH="../../common/lib")

conf = pEnv.Configure()
depDict = detect_deps.importDeps(env, "../../common/lib/qserv_common")
detect_deps.checkLibsFromDict(conf, depDict)
conf.CheckLib('qserv_common', language="C++")
cEnv = conf.Finish()

