# -*- python -*-

Import('env')
Import('standardModule')

standardModule(env, exclude='./czarProxy_wrap.cc')

build_data = DefaultEnvironment()['build_data']

# install Lua file
build_data['install'] += env.Install("$prefix/proxy", "mysqlProxy.lua")

# SWIG -Lua wrapper
swigged = env.SharedObject(source="czarProxy.i",
                           SWIGFLAGS=['-lua', '-c++', '-Iinclude'],
                           SWIGPATH=['..'])

build_data['module_objects']['proxy'] += swigged
