# -*- python -*-
Import('env')
Import('extraTgts')

proxyFiles = [env.File("mysqlProxy.lua"),
              env.File("startMySQLProxy")]
for p in proxyFiles:
    extraTgts["dist"].append(("proxy", p))

