# -*- python -*-

Import('env')
Import('standardModule')

standardModule(env)

build_data = DefaultEnvironment()['build_data']

# install Lua file
build_data['install'] += env.Install("$prefix/share/lua/qserv", "mysqlProxy.lua")
