-- MySQL Script generated by MySQL Workbench
-- Thu Jul 30 11:58:38 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema qservCssData
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qservCssData
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qservCssData` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `qservCssData`;

-- -----------------------------------------------------
-- Table `qservCssData`.`kvData`
-- -----------------------------------------------------
CREATE TABLE `qservCssData`.`kvData` (
  `kvId` INT NOT NULL AUTO_INCREMENT,
  `kvKey` CHAR(255) NOT NULL COMMENT 'slash delimited path',
  `kvVal` TEXT(1024) NOT NULL COMMENT 'value for key',
  `parentKvId` INT NULL COMMENT 'id of parent key',
  PRIMARY KEY (`kvId`),
  CONSTRAINT `kvData_parent_key`
    FOREIGN KEY (parentKvId)
    REFERENCES kvData(kvId),
  UNIQUE INDEX `kvData_kvKey_UNIQUE` (`kvKey` ASC)
) ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

