# This file is part of qserv.
#
# Developed for the LSST Data Management System.
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License

from collections import namedtuple
from filecmp import dircmp
import json
import logging
import os
import re
import shutil
import time
import subprocess
from urllib.parse import urlparse
import yaml

_log = logging.getLogger(__name__)


default_async_timeout = 600 # seconds

query_mode_mysql = "mysql"
query_mode_qserv_attached = "qserv_attached"
query_mode_qserv_detached = "qserv_detached"


class ITestQuery:
    """Represents a query to execute, with utilties for loading the query from a file.

    Parameters
    ----------
    query_file : `str`
        A file that contains a query to execute, may contain tags to be replaced
        and pragmas used during execution.
    output_dir : `str`
        The location where generated artifacts can be written and read for
        comparison.
    qserv_db_uri : `str`
        The uri to use to connect to qserv.
    msyql_db_uri : `str`
        The uri to use to connect to the mysql reference database.
    modes : `list` [`str`]
        Any/all of "sync", "async", "mysql". Sync and async run the tests in
        qserv, mysql runs the tests in the mysql reference database. Optional,
        defaults to ["sync", "async", "mysql"]
    """

    def __init__(self, query_file, output_dir, modes=None):
        self.query_file = query_file
        with open(self.query_file, "r") as f:
            self.query_t = f.read()
        pragmas = self._get_pragmas(self.query_t)
        self.output_dir = output_dir
        self.modes = ["sync", "async", "mysql"] if modes is None else modes
        # execute the query (rewrite from benchmark)
        # do results postprocessing - maybe in a helper. rewrite from benchmark.
        self.column_names = "noheader" not in pragmas
        self.no_async = "no_async" in pragmas
        self.async_timeout = int(pragmas.get("async_timeout", default_async_timeout)) if not self.no_async else None
        self.sort_result = "sortresult" in pragmas
        self.out_file_t = os.path.join(self.output_dir, "{mode}", os.path.basename(self.query_file).replace('.sql', '.txt'))
        _log.debug(f"ITestQuery query_file:{query_file}, out_file:{self.out_file_t}, modes:{modes}, "
                   f"column_names:{self.column_names}, no_async:{self.no_async}, "
                   f"async_timeout:{self.async_timeout}, sort_result:{self.sort_result}")

    def _run(self, args, outfile=None):
        """Run a prepared command.
        Checks the return code & raises if it is not 0.

        Parameters
        ----------
        args : `list` [`str`]
            The parameters to subprocess.run
        outfile : `str` or `None`
            If not `None`, will write stdout to a file at the provided location,
            otherwise will return the captured stdout.

        Returns
        -------
        output : `str` or `None`
            If `stdout` is provided will return None. Otherwise will return the
            stdout generated by the subprocess.
        """
        def _do(stdout):
            result = subprocess.run(args, stdout=stdout, stderr=subprocess.PIPE)
            if result.returncode != 0:
                _log.debug(f"{' '.join(args)} failed stdout:{result.stdout}, stderr:{result.stderr}")
                if result.returncode != 0:
                    _log.error(f"run command failed. stdout:{result.stdout}, stderr:{result.stderr}")
                result.check_returncode()
            return result.stdout

        if outfile is None:
            return _do(subprocess.PIPE)
        else:
            os.makedirs(os.path.dirname(outfile), exist_ok=True)
            with open(outfile, "w") as f:
                _do(f)
                if self.sort_result:
                    self._sort(outfile)

    def _sort(self, file):
        """Sort the lines in a result file.

        Parameters
        ----------
        file : `str`
            The path to a file whose lines will be sorted.
        """
        with open(file, "r+b") as f:
            sortedLines = sorted(f.readlines())
            f.seek(0)
            f.writelines(sortedLines)

    def run_detached(self, connection, qserv, database):
        """Run the query on the db at connection using SUBMIT, and then fetch
        results when they are available.

        Parameters
        ----------
        connection : `str`
            URI to the database to run the query on.
        qserv : `bool`
            True if the query is being run on a qserv instance.
        database : `str`
            TODO
        """
        query = self._render_query(self.query_t, qserv, database)
        parsed = urlparse(connection)
        args = [
            "mysql",
            "--host",
            f"{parsed.hostname}",
            f"--port={parsed.port}",
            f"--user={parsed.username}",
            "--batch",
            "--skip-column-names",
            "--database",
            database,
            "-e",
            f"SUBMIT {query}",
        ]
        data = self._run(args)
        try:
            query_id = int(data.split()[0])
            _log.debug(f"SQLCmd.execute query ID = {query_id}")
        except Exception:
            raise RuntimeError(f"Failed to read query ID from SUBMIT: {data}")
            # wait until query completes
        args = [
            "mysql",
            "--host",
            f"{parsed.hostname}",
            f"--port={parsed.port}",
            f"--user={parsed.username}",
            "--batch",
            "--skip-column-names",
            "-e",
            f"SELECT STATE FROM INFORMATION_SCHEMA.PROCESSLIST WHERE ID = {query_id}",
        ]
        _log.debug("SQLCmd.execute waiting for query to complete")
        end_time = time.time() + self.async_timeout
        while time.time() < end_time:
            status = self._run(args).strip()
            _log.debug(f"SQLCmd.execute query status = {status}")
            if status == b"COMPLETED":
                break
        else:
            raise RuntimeError("Timeout while waiting for detached query")

        args = [
            "mysql",
            "--host",
            f"{parsed.hostname}",
            f"--port={parsed.port}",
            f"--user={parsed.username}",
            "--batch",
            "-e",
            f"SELECT * from qserv_result({query_id})",
        ]
        if not self.column_names:
            args.insert(1, "--skip-column-names")
        self._run(args, self.out_file_t.format(mode=query_mode_qserv_detached))

    def run_attached(self, connection, qserv, database):
        """Run the query on the db at the given connection
        attached/synchronously - do not SUBMIT and wait for result.

        Parameters
        ----------
        connection : `str`
            URI to the database to run the query on.
        qserv : `bool`
            True if running on a qserv instance, False if running on a mysql instance.
        database : `str`
            TODO
        """
        query = self._render_query(self.query_t, qserv, database)
        parsed = urlparse(connection)
        # TODO strip pw from connection, or print parsed params.
        _log.debug(f"run_attached connection:{connection}, qserv:{qserv}")
        args = [
            "mysql",
            "--host",
            f"{parsed.hostname}",
            f"--port={parsed.port}",
            f"--user={parsed.username}",
            "--batch",
            "--database",
            database,
            "-e",
            query,
        ]
        if not self.column_names:
            args.insert(1, "--skip-column-names")
        self._run(args, self.out_file_t.format(mode=query_mode_qserv_attached if qserv else query_mode_mysql))

    def _get_pragmas(self, query):
        pragmas = {}
        for line in query.split("\n"):
            if not line.startswith("--"):
                continue
            # check for pragma, format is:
            #    '-- pragma keyval [keyval...]'
            #    where keyval is 'key=value' or 'key'
            words = line.split()
            if len(words) > 1 and words[1] == 'pragma':
                for keyval in words[2:]:
                    kv = keyval.split('=', 1) + [None]
                    pragmas[kv[0]] = kv[1]
        return pragmas

    def _render_query(self, query_t, with_qserv, database):
        """Reads a file with SQL query, filters it based on qserv/mysql mode.

        Parameters
        ----------
        query_file : file object
            Open file with query text and extra stuff.
        with_qserv : bool
            If `True` then prepare query for QServ, otherwise for mysql.
        database: `str`
            The database name to replace tag {DBTAG_A} with; "{database}." will
            be substitued in the query text.

        Returns
        -------
        query : `str`
            The query text.
        """
        qText = []
        for line in query_t.split("\n"):
            # squeeze/strip spaces
            line = line.strip()
            line = re.sub(' +', ' ', line)
            if not line:
                # skip empty lines
                pass
            elif with_qserv and line.startswith("-- withQserv"):
                # strip the "-- withQserv" text
                qText.append(line[13:])
            elif line.endswith("-- noQserv"):
                if with_qserv:
                    # skip this line
                    pass
                else:
                    # strip the "-- noQserv" text
                    qText.append(line[:-10])
            elif not line.startswith("--"):
                # append all non-commented lines
                qText.append(line)
        query = ' '.join(qText)
        if database:
            query = query.format(DBTAG_A=f"{database}.")
        return query


class ITestCase:

    def __init__(self, case_id, sourcedir, outdir, mysql_connection, qserv_connection, skip_numbers):
        # if outdir exists, do something (fail? erase?)
        self.case_id = case_id
        self.queries_dir = os.path.join(sourcedir, "queries")
        self.outdir = outdir
        self.mysql_connection = mysql_connection
        self.qserv_connection = qserv_connection
        self.skip_numbers = skip_numbers or []
        with open(os.path.join(sourcedir, "data/ingest/database.json")) as f:
            self.db_name = json.load(f)["database"]
        if os.path.exists(self.outdir):
            shutil.rmtree(self.outdir)
        _log.debug(f"ITestCase queries_dir:{self.queries_dir}, outdir={self.outdir}, db_name:{self.db_name}, skip_numbers:{skip_numbers}")

    def run(self):
        _log.info(f"Running {self.case_id}")
        for query_file in os.listdir(self.queries_dir):
            if "FIXME" in query_file:
                _log.info(f"Skipping FIXME query {os.path.basename(query_file)}")
                continue
            if query_file.split("_")[0] in self.skip_numbers:
                _log.info(f"Skipping 'skip_number' query {os.path.basename(query_file)}")
                continue
            _log.info(f"Running query {os.path.basename(query_file)}")
            query = ITestQuery(os.path.join(self.queries_dir, query_file), self.outdir)
            query.run_attached(self.mysql_connection, qserv=False, database=self.db_name)
            query.run_attached(self.qserv_connection, qserv=True, database=self.db_name)
            query.run_detached(self.qserv_connection, qserv=True, database=self.db_name)


class ITestCaseResult:
    def __init__(self, case_name):
        self.case_name = case_name
        self.diffs = {}

    def add_diffs(self, mode, diffs):
        d = self.diffs.get(mode, [])
        d.extend(diffs)
        self.diffs[mode] = d

    @property
    def passed(self):
        return not self.diffs

    def __str__(self):
        if self.passed:
            ret = f"Test case {self.case_name} passed."
        else:
            ret = f"Test case {self.case_name} FAILED, failing queries: "
            ret += ", ".join(f"{mode}: [{', '.join(queries)}]" for mode, queries in self.diffs.items())
        return ret

def run_queries(source, output, mysql, qserv, run_cases, test_cases_data):
    """Run queries.

    Parameters
    ----------
    source : `str`
        The folder containing integration test "cases". Each folder in the dir should be named "caseNN"
        and contain a folder called "queries". All the files ending in .sql in the queries folder will
        be run in qserv (sync and async) and in mysql and outputs will be saved at TODO.
    output : `str`
        The folder where output datasets can be written.
    mysql : `str`
        TODO
    qserv : `qserv`
        TODO
    run_cases : `list` [`str`] or `None`
        The test cases to run, or `None` if all cases should be run.
    test_cases_data : `dict`
        Dict of test cases that contain data about the cases to run.
    """

    def get_cases():
        """Generator for test cases."""
        # TODO there is a dependency here that the case names in the load.yaml file
        # match the case names (folder names) for each test case. Maybe that's a
        # good thing even, but right now it's not formal, and might want to be
        # formalized.

        for case_data in test_cases_data:
            if not run_cases or case_data["id"] in run_cases:
                yield ITestCase(
                    case_data["id"],
                    os.path.join(source, case_data["id"]),
                    os.path.join(output, case_data["id"]),
                    mysql,
                    qserv,
                    case_data.get("skip_numbers", None)
                )

    for case in get_cases():
        case.run()


def compareQueryResults(run_cases, outputs_dir):
    """Compare results from runs with different modes.

    Parameters
    ----------
    run_cases : `list` [`str`] or `None`
        The test cases to run, or `None` if all cases should be run.
    outputs_dir : `str`
        The folder where output datasets can be written.
    """
    all_cases_passed = True
    results = []
    cases = list(run_cases or os.listdir(outputs_dir))
    cases.sort()
    for case in cases:
        _log.debug(f"Comparing {case}")
        if not os.path.exists(os.path.join(outputs_dir, case)):
            _log.warn(f"There are no query results to compare for {case}.")
            continue
        comparisons = (
            (query_mode_mysql, query_mode_qserv_attached),
            (query_mode_mysql, query_mode_qserv_detached),
        )
        result = ITestCaseResult(case)
        for reference, testdir in comparisons:
            r = os.path.join(outputs_dir, case, reference)
            t = os.path.join(outputs_dir, case, testdir)
            cmp = dircmp(r, t)
            diffs = cmp.left_only + cmp.right_only + cmp.diff_files
            if not diffs:
                _log.debug(f"{reference} and {testdir} results are identical.")
            else:
                _log.debug(f"{reference} and {testdir} differ for {len(diffs)} queries: {diffs}")
                result.add_diffs(testdir, diffs)
        results.append(result)

    for result in results:
        _log.info(str(result))

    return all_cases_passed
