{{- if .Values.ingest.enable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingest-config
  labels:
    {{- include "qserv.labels" . | nindent 4 }}
data:
  # change 80 to 8080 as openshift does not allow binds to ports < 1024
  default.conf: |
    server {
      listen 8080;
      server_name localhost;
      location / {
        root /qserv/data/html;
        index index.html index.htm;
      }
    }
{{- end }}
