apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "qserv.name" . }}-repl
  labels:
    {{- include "qserv.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "qserv.name" . }}-repls
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "qserv.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: repl
  template:
    metadata:
      labels:
        {{- include "qserv.labels" . | nindent 8 }}
        app.kubernetes.io/component: repl
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: qserv.lsst.io/tier
                operator: In
                values: [ utility ]
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values: [ {{ include "qserv.name" . }} ]
              - key: app.kubernetes.io/instance
                operator: In
                values: [ {{ .Release.Name }} ]
              - key: app.kubernetes.io/component
                operator: In
                values: [ utility ]
            topologyKey: kubernetes.io/hostname
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: mariadb
        image: {{ .Values.mariadbImageName | quote }}
        imagePullPolicy: {{ .Values.mariadbImagePullPolicy | quote }}
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: repl-secrets
              key: mariadb-root-password
        startupProbe:
          exec:
            command:
              - bash
              - -ec
              - |
                mariadb-admin --protocol=TCP -h 127.0.0.1 --connect-timeout=2 -uroot -p"$$MARIADB_ROOT_PASSWORD" ping
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 60
        readinessProbe:
          exec:
            command:
              - bash
              - -ec
              - |
                mariadb --protocol=TCP -h 127.0.0.1 --connect-timeout=2 -uroot -p"$$MARIADB_ROOT_PASSWORD" -N -e "SELECT 1"
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          exec:
            command:
              - bash
              - -ec
              - |
                mariadb-admin --protocol=TCP -h 127.0.0.1 --connect-timeout=2 -uroot -p"$$MARIADB_ROOT_PASSWORD" ping
          periodSeconds: 10
          timeoutSeconds: 3
        volumeMounts:
        - name: mariadb-config
          mountPath: /etc/mysql/conf.d/99-qserv-repl.cnf
          subPath: 99-qserv-repl.cnf
          readOnly: true
        - name: tmp
          mountPath: /tmp
        - name: repl-data
          mountPath: /qserv/data
      volumes:
      - name: mariadb-config
        configMap:
          name: repl-config
          items:
          - key: 99-qserv-repl.cnf
            path: 99-qserv-repl.cnf
      - name: tmp
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: repl-data
      labels:
        {{- include "qserv.labels" . | nindent 8 }}
    spec:
      accessModes: [ ReadWriteOnce ]
      storageClassName: {{ .Values.replication.mariadb.storage.class | quote }}
      resources:
        requests:
          storage: {{ .Values.replication.mariadb.storage.size | quote }}
