apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  labels:
    {{- include "qserv.labels" . | nindent 4 }}
data:
  99-qserv-worker.cnf: |
    [mysqld]
    datadir=/qserv/data/mysql
    max-connections=16384
    connect_timeout=28800
    net_read_timeout=90000
    net_write_timeout=90000
    wait_timeout=90000
    symbolic-links=0
    tmp_table_size=4G
    max_heap_table_size=4G
    myisam_sort_buffer_size=16G
    myisam_repair_threads=2
    use_stat_tables='preferably'
    optimizer_use_condition_selectivity=3
    query-cache-size=0
    join-buffer-size=4G
