version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: "Dependabot"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "xrd"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: "Dependabot"
    open-pull-requests-limit: 5
