# whitelist
branches:
  only:
      - tickets/DM-5218

sudo: required

services:
      - docker

before_install:
    - cp ./admin/tools/docker/integration-tests/localhost/env.example.sh ./admin/tools/docker/integration-tests/localhost/env.sh

script:
    - ./admin/tools/docker/integration-tests/localhost/run-multinode-tests.sh
