# whitelist
branches:
  only:
    - master
    - /^tickets\/.*$/

sudo: false

services:
  - docker

before_install:
  - docker pull qserv/qserv:dev
  - cp ./admin/tools/docker/integration-tests/travis/env.sh .

script:
  - ./admin/tools/docker/3_build-git-image.sh -L -T travis -S "$PWD"
  - ./admin/tools/docker/4_build-configured-images.sh -L -i travis master.localdomain
  - ./admin/tools/docker/integration-tests/localhost/run-multinode-tests.sh
