#!/bin/bash
#
# qms		This shell script takes care of starting and stopping
#		qms (Qserv Meta Service).
#
# description: qms is the Qserv Meta Service. \
# It is used by Qserv master in order to get accurate informations \
# about loaded dataset. \
# Note that Qserv service won't start if QMS databse is empty.

### BEGIN INIT INFO
# Provides: qms
# Short-Description: start and stop qms
# Description: qms is the Qserv Meta Service. It is used by Qserv master
#              in order to get accurate informations about loaded datasets.
#              Note that Qserv service won't start if QMS databse is empty.
### END INIT INFO

. %(QSERV_BASE_DIR)s/etc/init.d/qserv-functions

SERVICE_NAME="Qserv Metadata Server (QMS)"
prog="qms"

PYTHON=%(QSERV_BASE_DIR)s/bin/python

START=%(QSERV_BASE_DIR)s/qserv/meta/bin/startQMS.py
CONFIG=%(QSERV_BASE_DIR)s/etc/qms.cnf
pidfile=%(QSERV_PID_DIR)s/${prog}.pid
lockfile=%(QSERV_BASE_DIR)s/var/lock/subsys/${prog}
LOGFILE=%(QSERV_LOG_DIR)s/${prog}-startup.log

cmd="${PYTHON} ${START} -c ${CONFIG} &> ${LOGFILE} &"

# See how we were called.
case "$1" in
  start)
	start -p $pidfile -l $lockfile $prog "${cmd}"
	;;
  stop)
	stop -p $pidfile -l $lockfile $prog
	;;
  status)
	status -p ${pidfile} $prog
	RETVAL=$?
	;;
  restart)
	stop -p $pidfile -f $lockfile $prog
	start
	;;
  try-restart|condrestart)
	if status -p ${pidfile} $prog > /dev/null; then
	    stop
	    start
	fi
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|try-restart}"
	exit 2
esac