/* 
 * LSST Data Management System
 * Copyright 2015 AURA/LSST.
 * 
 * This product includes software developed by the
 * LSST Project (http://www.lsst.org/).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the LSST License Statement and 
 * the GNU General Public License along with this program.  If not, 
 * see <https://www.lsstcorp.org/LegalNotices/>.
 */
#ifndef LSST_QSERV_QMETA_EXCEPTIONS_H
#define LSST_QSERV_QMETA_EXCEPTIONS_H

// System headers

// Third-party headers
#include "boost/lexical_cast.hpp"

// Qserv headers
#include "sql/SqlErrorObject.h"
#include "util/Issue.h"

namespace lsst {
namespace qserv {
namespace qmeta {

/// @addtogroup qmeta

/**
 *  @ingroup qmeta
 *
 *  @brief Base class for exceptions generated by qmeta module.
 */

class Exception : public util::Issue {
public:
    Exception(util::Issue::Context const& ctx, std::string const& message)
        : util::Issue(ctx, message)
    {}
};

/// Exception thrown when czar name is not known.
class CzarNameError : public Exception {
public:
    CzarNameError(util::Issue::Context const& ctx, std::string const& name)
        : Exception(ctx, "Czar is not registered in metadata: " + name)
    {}
};

/// Exception thrown when czar ID is not known.
class CzarIdError : public Exception {
public:
    CzarIdError(util::Issue::Context const& ctx, int id)
        : Exception(ctx, "Czar ID is not registered in metadata: " + boost::lexical_cast<std::string>(id))
    {}
};

/// Exception thrown when query ID is not known.
class QueryIdError : public Exception {
public:
    QueryIdError(util::Issue::Context const& ctx, int id)
        : Exception(ctx, "Query ID is not registered in metadata: " + boost::lexical_cast<std::string>(id))
    {}
};

/// Exception thrown when chunk ID is not known.
class ChunkIdError : public Exception {
public:
    ChunkIdError(util::Issue::Context const& ctx, int queryId, int chunkId)
        : Exception(ctx, "Chunk ID is not registered in metadata: " +
                    boost::lexical_cast<std::string>(chunkId) + " query id:" +
                    boost::lexical_cast<std::string>(queryId))
    {}
};

/// Exception thrown when chunk ID is not known.
class SqlError : public Exception {
public:
    SqlError(util::Issue::Context const& ctx, sql::SqlErrorObject const& sqlErr)
        : Exception(ctx, "Error from mysql: (" + boost::lexical_cast<std::string>(sqlErr.errNo()) +
                    ") " + sqlErr.errMsg())
    {}
};

/// Exception thrown when one or more metadata tables are missing.
class MissingTableError : public Exception {
public:
    MissingTableError(util::Issue::Context const& ctx, std::string const& table)
        : Exception(ctx, "Query metadata table is missing: " + table)
    {}
};

/// Exception thrown when database consistency is violated.
class ConsistencyError : public Exception {
public:
    ConsistencyError(util::Issue::Context const& ctx, std::string const& msg)
        : Exception(ctx, "Metadata consistency error: " + msg)
    {}
};

}}} // namespace lsst::qserv::qmeta

#endif // LSST_QSERV_QMETA_EXCEPTIONS_H
