# -*- python -*-
import os

Import('env')
Import('standardModule')

# PYTHON_INC_DIR is set by pymod tool
pythonInc = env['PYTHON_INC_DIR']
cppPath = env['CPPPATH'] + [pythonInc]

# pybind11 Python wrapper goes to a separate library, cc file is also
# excluded from standardModule()
# pybind11 makes too many warnings when built with -pedantic
ccflags = [flag for flag in env['CCFLAGS'] if flag != '-pedantic']
py_wrapper = env.SharedObject("qmetaPythonWrapper.cc", CPPPATH=cppPath, CCFLAGS=ccflags)

build_data = DefaultEnvironment()['build_data']
build_data['module_objects']['qmeta:python'] = py_wrapper

# runs standard stuff _after_ above to install Python module
standardModule(env,  exclude="./qmetaPythonWrapper.cc",
               unit_tests=[])

# install schema files
build_data['install'] += env.Install("$prefix/share/qserv/schema/qmeta", env.Glob("schema/*.sql"))
