#
# Config file for test script
#

queryClasses:

  LV:
    concurrentQueries: 80  # how many concurrent queries to run
    targetTime: 10s  # not really used
    maxRate: 100  # maximum query submission rate, Hz
    arraysize: 1000

  FTSObj:
    concurrentQueries: 12
    targetTimeSec: 1h
    maxRate: null  # null means no limit, it is default
    arraysize: null  # null means default

  FTSSrc:
    concurrentQueries: 3
    targetTimeSec: 12h

  FTSFSrc:
    concurrentQueries: 3
    targetTimeSec: 12h

  joinObjSrc:
    concurrentQueries: 6
    targetTimeSec: 12h

  joinObjFSrc:
    concurrentQueries: 3
    targetTimeSec: 12h

  nearN:
    concurrentQueries: 3
    targetTimeSec: 1h

queries:

  LV:
    # key (q1) is an identifier, for monitoring purposes
    q1:
      template: >
        SELECT ra, decl, raVar, declVar, radeclCov, u_psfFlux, u_psfFluxSigma, u_apFlux
        FROM Object
        WHERE deepSourceId = {objectId}
      variables:
        objectId:
          path: /path/to/file.txt
          mode: random
    q2:
      template: >
        SELECT ra, decl, raVar, declVar, radeclCov, u_psfFlux, u_psfFluxSigma, u_apFlux
        FROM Object
        WHERE qserv_areaspec_box({raMin}, {declMin}, {raMin}+{raDist}, {declMin}+{declDist})
      variables:
        raMin: {distribution: uniform, min: 0, max: 350}
        declMin: {distribution: uniform, min: -87, max: 45}
        raDist: {distribution: uniform, min: 0.01, max: 0.2}
        declDist: {distribution: uniform, min: 0.01, max: 0.2}
    q3:
      template: >
        SELECT o.deepSourceId, o.ra, o.decl, s.coord_ra, s.coord_decl, s.parent
        FROM Object o, Source s
        WHERE qserv_areaspec_box({raMin}, {declMin}, {raMin}+{raDist}, {declMin}+{declDist}) and o.deepSourceId = s.objectId
      variables:
        raMin: {distribution: uniform, min: 0, max: 350}
        declMin: {distribution: uniform, min: -87, max: 45}
        raDist: {distribution: uniform, min: 0.01, max: 0.2}
        declDist: {distribution: uniform, min: 0.01, max: 0.2}

  FTSObj:
    q1: "SELECT COUNT(*) FROM Object WHERE y_instFlux > 0.05"
    q2: "SELECT ra, decl, u_psfFlux, g_psfFlux, r_psfFlux FROM Object WHERE y_shapeIxx BETWEEN 20 AND 40"
    q3: "SELECT COUNT(*) FROM Object WHERE y_instFlux > u_instFlux"
    q4: "SELECT MIN(ra), MAX(ra) FROM Object WHERE decl > 3"
    q5: "SELECT MIN(ra), MAX(ra) FROM Object WHERE z_apFlux BETWEEN 1 and 2"
    q6: "SELECT MIN(ra), MAX(ra), MIN(decl), MAX(decl) FROM Object"
    q7: "SELECT MIN(ra), MAX(ra), MIN(decl), MAX(decl) FROM Object WHERE z_instFlux < 3"
    q8: "SELECT COUNT(*) AS n, AVG(ra), AVG(decl), chunkId FROM Object GROUP BY chunkId"
    # q9: "SELECT deepSourceId, u_apFluxSigma FROM Object WHERE u_apFluxSigma between 0 and 0.02",       # 1,889,695,615 rows / ~28 GB
    # q10: "SELECT deepSourceId, u_apFluxSigma FROM Object WHERE u_apFluxSigma between 0 and 2.27e-30",   #   475,244,843 rows / ~ 7 GB
    # q11: "SELECT deepSourceId, u_apFluxSigma FROM Object WHERE u_apFluxSigma between 0 and 2e-30",      #    42,021,567 rows / ~ 0.5 GB
    q12: "SELECT deepSourceId, u_apFluxSigma FROM Object WHERE u_apFluxSigma between 0 and 1.75e-30"    #     1,932,988 rows / ~ 29 MB
    q13: "SELECT deepSourceId, u_apFluxSigma FROM Object WHERE u_apFluxSigma between 0 and 1.8e-30"
    q14: "SELECT deepSourceId, u_apFluxSigma FROM Object WHERE u_apFluxSigma between 0 and 1.81e-30"
    q15: "SELECT deepSourceId, u_apFluxSigma FROM Object WHERE u_apFluxSigma between 0 and 1.5e-30"      # 119,423 rows / ~ 2 MB

  FTSSrc:
    q1: "SELECT COUNT(*) FROM Source WHERE flux_sinc BETWEEN 1 AND 2"

  FTSFSrc:
    q1: "SELECT COUNT(*) FROM ForcedSource WHERE psfFlux BETWEEN 0.1 AND 0.2"

  joinObjSrc:
    q1: "SELECT o.deepSourceId, s.objectId, s.id, o.ra, o.decl FROM Object o, Source s WHERE o.deepSourceId=s.objectId AND s.flux_sinc BETWEEN 0.13 AND 0.14"
    q2: "SELECT o.deepSourceId, s.objectId, s.id, o.ra, o.decl FROM Object o, Source s WHERE o.deepSourceId=s.objectId AND s.flux_sinc BETWEEN 0.3 AND 0.31"
    q3: "SELECT o.deepSourceId, s.objectId, s.id, o.ra, o.decl FROM Object o, Source s WHERE o.deepSourceId=s.objectId AND s.flux_sinc BETWEEN 0.7 AND 0.72"

  joinObjFSrc:
    q1: "SELECT o.deepSourceId, f.psfFlux FROM Object o, ForcedSource f WHERE o.deepSourceId=f.deepSourceId AND f.psfFlux BETWEEN 0.13 AND 0.14"

  nearN:
    q1:
      template: >
        select count(*)
        from Object o1, Object o2
        where qserv_areaspec_box(%f, %f, %f, %f) and scisql_angSep(o1.ra, o1.decl, o2.ra, o2.decl) < 0.015
      variables:
        raMin: {distribution: uniform, min: 0, max: 340}
        declMin: {distribution: uniform, min: -87, max: 40}
        raDist: {distribution: uniform, min: 8, max: 12}
        declDist: {distribution: uniform, min: 8, max: 12}
