# -*- python -*-
Import("env")
import glob

for src in glob.glob("*.cc"):
    env.Program(src, LIBS=env.getlibs(env["eups_product"]))

#
# Tests
#
import lsst.tests

suffix = env['LDMODULESUFFIX']
tests = lsst.tests.Control(env, verbose = True)
for target in tests.run("*.cc"):
    env.Depends(target, "../lib/libqserv_worker%s" % (suffix,))

for target in tests.run("*.py"):
    env.Depends(target, "../python/lsst/qserv/worker/_workerLib%s" % (suffix,))
