/*
 * LSST Data Management System
 *
 * This product includes software developed by the
 * LSST Project (http://www.lsst.org/).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the LSST License Statement and
 * the GNU General Public License along with this program.  If not,
 * see <http://www.lsstcorp.org/LegalNotices/>.
 */
#ifndef LSST_QSERV_PROTOJSON_CHUNKUSECOUNTANSWER_H
#define LSST_QSERV_PROTOJSON_CHUNKUSECOUNTANSWER_H

// System headers
#include <chrono>
#include <map>
#include <memory>
#include <string>

// Third party headers
#include "nlohmann/json.hpp"

// qserv headers
#include "global/clock_defs.h"
#include "global/intTypes.h"

namespace lsst::qserv::wpublish {
class ChunkStatistics;
}

namespace lsst::qserv::protojson {

/// This class is used to handle the chunk use request messages. It converts json messages
/// to and from DbChunkCountMapPtr objects, which are generated by workers using the
/// QueriesAndChunks class.
class ChunkUseCountAnswerMsg {
public:
    using Ptr = std::shared_ptr<ChunkUseCountAnswerMsg>;
    typedef std::map<int, int> ChunkCountMap;  ///< Map of chunkId to useCount for a specific database.
    typedef std::map<std::string, ChunkCountMap> DbChunkCountMap;
    typedef std::shared_ptr<DbChunkCountMap> DbChunkCountMapPtr;

    ChunkUseCountAnswerMsg() = delete;

    static Ptr create(DbChunkCountMapPtr const& chunkStatsMap_) {
        return Ptr(new ChunkUseCountAnswerMsg(chunkStatsMap_));
    }

    static Ptr createFromJson(nlohmann::json const& json);

    nlohmann::json toJson() const;
    bool equal(ChunkUseCountAnswerMsg const& other) const;

private:
    ChunkUseCountAnswerMsg(DbChunkCountMapPtr const& chunkStatsMap_) : _dbchunkCountMap(chunkStatsMap_) {}

    DbChunkCountMapPtr _dbchunkCountMap;  ///< Map of database name to map of chunkId to useCount.
};

}  // namespace lsst::qserv::protojson

#endif  // LSST_QSERV_PROTOJSON_CHUNKUSECOUNTANSWER_H
