#!/bin/bash

#start_mysqlproxy
LUAROOT=%(QSERV_BASE_DIR)s
LUASHARE=$LUAROOT/share/lua/5.1
LUALIB=$LUAROOT/lib/lua/5.1
LUAPATH="$LUASHARE/?.lua;$LUASHARE/?/init.lua;$LUASHARE/?/?.lua"
LUACPATH="$LUALIB/?.so;$LUALIB/?/?.so"
DEBUG=0 QSERV_RPC_PORT=%(QSERV_RPC_PORT)s %(QSERV_BASE_DIR)s/bin/mysql-proxy --defaults-file=%(QSERV_BASE_DIR)s/etc/my-proxy.cnf --lua-path=$LUAPATH --lua-cpath=$LUACPATH &> %(QSERV_LOG_DIR)s/mysql-proxy-lua.log &
