#!/bin/bash

#start_mysqlproxy
LUAROOT=%(QSERV_BASE_DIR)s
QSERVDIST=%(QSERV_BASE_DIR)s/qserv/master/proxy/
LUASHARE=$LUAROOT/share/lua/5.1
LUALIB=$LUAROOT/lib/lua/5.1
LUAPATH="$LUASHARE/?.lua;$LUASHARE/?/init.lua;$LUASHARE/?/?.lua"
LUACPATH="$LUALIB/?.so;$LUALIB/?/?.so"
%(QSERV_BASE_DIR)s/bin/mysql-proxy --proxy-lua-script=$QSERVDIST/mysqlProxy.lua --defaults-file=%(QSERV_BASE_DIR)s/etc/my-proxy.cnf --lua-path=$LUAPATH --lua-cpath=$LUACPATH &
echo $! > %(QSERV_PID_DIR)s/mysql-proxy.pid
