#!/bin/bash

#start_qserv
export PATH=/%(QSERV_BASE_DIR)s/bin:$PATH
XRD_DIR=%(QSERV_BASE_DIR)s/xrootd
PLATFORM=x86_64_linux_26_dbg
PYTHON=%(QSERV_BASE_DIR)s/bin/python
export PYTHONPATH=%(QSERV_BASE_DIR)s/qserv/master/dist
export LD_LIBRARY_PATH=%(QSERV_BASE_DIR)s/lib:$XRD_DIR/lib/$PLATFORM
export QSW_RESULTDIR=%(QSERV_BASE_DIR)s/qserv-run/tmp
# Disabling buffering in python in order to enable "real-time" logging.
export PYTHONUNBUFFERED=1
$PYTHON %(QSERV_BASE_DIR)s/qserv/master/dist/startQserv.py -c %(QSERV_BASE_DIR)s/etc/local.qserv.cnf > %(QSERV_LOG_DIR)s/qserv.log &
echo $! > %(QSERV_PID_DIR)s/qserv.pid