#!/bin/bash

#start_xrootd
export QSW_XRDQUERYPATH="/q"
export QSW_DBSOCK="%(MYSQLD_SOCK)s"
export QSW_MYSQLDUMP="%(QSERV_BASE_DIR)s/bin/mysqldump"
QSW_SCRATCHPATH="%(QSERV_BASE_DIR)s/tmp"
QSW_SCRATCHDB="qservScratch"
export QSW_RESULTPATH="%(XROOTD_RUN_DIR)s/result"

export LD_LIBRARY_PATH="%(XROOTD_RUN_DIR)s;%(QSERV_BASE_DIR)s/lib"

# cmsd won't start if no manager is specified
%(COMMENT_MONO_NODE)s%(QSERV_BASE_DIR)s/bin/x86_64_linux_26_dbg/cmsd -c %(QSERV_BASE_DIR)s/etc/lsp.cf -l %(QSERV_LOG_DIR)s/cmsd.log -n worker &
%(COMMENT_MONO_NODE)secho $! > %(XROOTD_PID_DIR)s/cmsd.pid 
%(QSERV_BASE_DIR)s/bin/x86_64_linux_26_dbg/xrootd -c %(QSERV_BASE_DIR)s/etc/lsp.cf -l %(QSERV_LOG_DIR)s/xrootd.log -n worker &
echo $! > %(XROOTD_PID_DIR)s/xrootd.pid 
