# -*- python -*-
Import('env')
Import('standardModule')

import os.path

# Harvest special binary products - files starting with the package's name
# followed by underscore:
#
#   tests_<something>.cc
#
# Then make a Scons target for each of those to be returned by the calling
# SConscript. Also add the source file into a list of sources to be excluded
# from the shared library product.

bin_cc_targets = {}
path = "."
for f in env.Glob(os.path.join(path, "tests_*.cc"), source=True, strings=True):
    bin_cc_targets[f] = ["qserv_common","util","protobuf","log","log4cxx"]

# Initiate the standard sequence of actions for this module by excluding
# the above discovered binary sources

standardModule(env, bin_cc_targets=bin_cc_targets, unit_tests="")
