DROP FUNCTION IF EXISTS qserv_angSep;
DROP FUNCTION IF EXISTS qserv_ptInSphBox;
DROP FUNCTION IF EXISTS qserv_ptInSphCircle;
DROP FUNCTION IF EXISTS qserv_ptInSphEllipse;
DROP FUNCTION IF EXISTS qserv_ptInSphPoly;
CREATE FUNCTION qserv_angSep RETURNS REAL SONAME 'libqserv_udf.so';
CREATE FUNCTION qserv_ptInSphBox RETURNS INTEGER SONAME 'libqserv_udf.so';
CREATE FUNCTION qserv_ptInSphCircle RETURNS INTEGER SONAME 'libqserv_udf.so';
CREATE FUNCTION qserv_ptInSphEllipse RETURNS INTEGER SONAME 'libqserv_udf.so';
CREATE FUNCTION qserv_ptInSphPoly RETURNS INTEGER SONAME 'libqserv_udf.so';
