DROP FUNCTION IF EXISTS qserv_angSep;
DROP FUNCTION IF EXISTS qserv_ptInSphBox;
DROP FUNCTION IF EXISTS qserv_ptInSphCircle;
DROP FUNCTION IF EXISTS qserv_ptInSphEllipse;
DROP FUNCTION IF EXISTS qserv_ptInSphPoly;
