# -*- python -*-
Import('env')

# Work done at top-level SConstruct right now
# import os, fnmatch

# pkg = env["eups_product"]
# sources = []
# for root, dirs, files in os.walk("../src"):
#     sources += [os.path.join(root, f) for f in fnmatch.filter(files, "*.cc")]
#     dirs = [d for d in dirs if not fnmatch.fnmatch(d, ".*")]
# env.SharedLibrary(pkg, sources,
#     LIBS=filter(lambda x: x != pkg, env.getlibs(pkg)))
