# -*- python -*-
Import('env')

lenv = env.Clone()
sources = lenv.Glob('[!Q]*.cc')
lenv.StaticLibrary('dupr', sources)

for target in ('qserv-htm-index',
               'qserv-partition',
               'qserv-partition-matches',
               'qserv-duplicate',
               'qserv-estimate-stats',
              ):
    source = ''.join(map(lambda s: s.title(), target.split('-'))) + '.cc'
    penv = env.Clone()
    penv.Append(LIBPATH=['.'])
    penv.Prepend(LIBS=['dupr'])
    program = penv.Program(target, [source])
    penv.Install('$PREFIX/bin', program)
