# -*- python -*-
Import('env')
Import('standardModule')

# Construct proto env (add protoc Builder)
proto = File("worker.proto")
pFiles = env.Protoc(
    proto,
    PROTOC_PATH='.',
    PROTOC_CCOUT='.',
    PROTOC_PYOUT='.',
)

standardModule(env, test_libs='log4cxx')
