# -*- python -*-
import os

Import('env')
Import('standardModule')

# PYTHON_INC_DIR is set by pymod tool
pythonInc = env['PYTHON_INC_DIR']
cppPath = env['CPPPATH'] + [pythonInc]

# pybind11 Python wrapper goes to a separate library, cc file is also
# excluded from standardModule()
# pybind11 makes too many warnings when built with -pedantic
ccflags = [flag for flag in env['CCFLAGS'] if flag != '-pedantic']
py_wrapper = env.SharedObject("diridxPythonWrapper.cc", CPPPATH=cppPath, CCFLAGS=ccflags)

build_data = DefaultEnvironment()['build_data']
build_data['module_objects']['diridx:python'] = py_wrapper

# runs standard stuff _after_ above to install Python module
standardModule(env, exclude="./diridxPythonWrapper.cc")
# TODO explicily add unit tests; see css SConsript for an example
