# -*- python -*-
# SConscript for parser module
Import('env')
Import('standardModule')

import os

standardModule(env)

antlr4LexerTgt = env.Antlr4(['QSMySqlLexer.g4'], ANTLR4_OUT='.')
# The exuction of the antlr4 tool on QSMySqlLexer.g4 (on the line above) generates
# `QSMySqlLexer.tokens` (used on the line below).
antlr4ParserTgt = env.Antlr4(['QSMySqlLexer.tokens', 'QSMySqlParser.g4'], ANTLR4_OUT='.')

antlr4Srcs = [f for f in (antlr4LexerTgt + antlr4ParserTgt) if str(f).endswith(env.subst('$ANTLR4_CCSUFFIX'))]
antlr4Hdrs = [f for f in (antlr4LexerTgt + antlr4ParserTgt) if str(f).endswith(env.subst('$ANTLR4_HSUFFIX'))]

build_data = DefaultEnvironment()['build_data']
build_data['module_objects']['parser'] += antlr4Srcs
