import pytarget

Import('env')
Import('extraTgts')

pyTargets = pytarget.getPyTargets(env, ["lsst","qserv","wmgr"], [])
extraTgts['dist'].extend(pyTargets)

for f in env.Glob("bin/*py"):
    extraTgts['dist'].append(('bin', f))
