# Parameters related to Openstack instructure
# WARN: automatically generated by provisionning script, do not edit

SWARM_NODE="lsst-fabricejammes-qserv-swarm"

# Used by shmux
HOSTNAME_TPL="lsst-fabricejammes-qserv-"
WORKER_LAST_ID="2"

printf -v MASTER "%s0" "$HOSTNAME_TPL"

for i in $(seq 1 "$WORKER_LAST_ID");
do
    printf -v WORKERS "%s %s%s" "$WORKERS" "$HOSTNAME_TPL" "$i"
done
