qservImageName:  qserv/lite-qserv:2025.11.1-rc1-28-gf75d26818
mariadbImageName: qserv/lite-mariadb:2025.11.1-rc1
sslProxyImageName: qserv/mysql-proxy-ssl:latest

qservImagePullPolicy: IfNotPresent
mariadbImagePullPolicy: IfNotPresent
sslProxyImagePullPolicy: IfNotPresent

mode: full  # full | db-only

czars:
  replicas: 1
  storage:
    class: rubin-qserv-storage
    size: 5Ti

workers:
  replicas: 72
  storage:
    class: rubin-qserv-storage
    size: 10Ti

replication:
  storage:
    class: rubin-qserv-storage
    size: 2Ti
