qservImageName:  qserv/lite-qserv:2025.12.1-rc1-43-gf9cc38c37
mariadbImageName: qserv/lite-mariadb:2025.12.1-rc1
sslProxyImageName: qserv/mysql-proxy-ssl:latest
ingestHelperImageName: qserv/lite-build:2025.12.1-rc1-41-g6f7d0801a

qservImagePullPolicy: IfNotPresent
mariadbImagePullPolicy: IfNotPresent
sslProxyImagePullPolicy: IfNotPresent
ingestHelperPullPolicy: IfNotPresent

mode: full  # full | db-only

czars:
  replicas: 1
  storage:
    class: rubin-qserv-storage
    size: 5Ti

workers:
  replicas: 72
  storage:
    class: rubin-qserv-storage
    size: 10Ti

replication:
  storage:
    class: rubin-qserv-storage
    size: 2Ti

ingest:
  enable: true
  storage:
    class: rubin-qserv-storage
    size: 200Gi
