# -*- python -*-
Import('env')
import os, fnmatch

sources = []
for root, dirs, files in os.walk("../src"):
    sources += [os.path.join(root, f) for f in fnmatch.filter(files, "*.cc")]
    dirs = [d for d in dirs if not fnmatch.fnmatch(d, ".*")]
env.Append(CPPPATH = ['../include'])
env.Replace(RPATH = env['LIBPATH'])
env.Append(RPATH = [os.path.realpath('.')])
lib = env.SharedLibrary("qserv_worker", sources)
env.Append(built_libs = [lib])
