// -*- LSST-C++ -*-
/* 
 * LSST Data Management System
 * Copyright 2012-2013 LSST Corporation.
 * 
 * This product includes software developed by the
 * LSST Project (http://www.lsst.org/).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the LSST License Statement and 
 * the GNU General Public License along with this program.  If not, 
 * see <http://www.lsstcorp.org/LegalNotices/>.
 */
#ifndef LSST_QSERV_MASTER_QUERYTEMPLATE_H
#define LSST_QSERV_MASTER_QUERYTEMPLATE_H
/**
  * @file 
  *
  * @author Daniel L. Wang, SLAC
  */
#include <string>
#include <list>
#include <boost/shared_ptr.hpp>

namespace lsst { namespace qserv { namespace master {
// Forward
class ColumnRef;
class TableRefN;

/// QueryTemplate
///
/// @brief QueryTemplate stores a query representation that is a sequence of
/// mostly-concrete tokens. It contains minimal structural information except
/// what is necessary to vary queries for different partitions. 
///
/// A query template is an intermediate stage between a fully-structured
/// semantic-preserving query representation (i.e., SelectStmt) and generated
/// query (a plain std::string). The purpose of the intermediate stage is to
/// provide a representation that can be manipulated quickly to generate batches
/// of queries that only differ in certain, fixed locations.

/// Query templates are constructed by appending tokens to a stream. Concrete
/// queries are generated by applying a mapping to the template and performing
/// substitutions at certain locations.

/// History:
/// QueryTemplate replaces the string-based Substitution class that was used to
/// perform fast chunk substitutions in generating queries. 
///
/// The Substition/SqlSubstitution model employed a single template
/// string along with an index to the string regions that were
/// substitutable. Callers provided a mapping (i.e., {Object ->
/// Object_2031, Object_s2 -> Object_2031_232} ) that was used to
/// perform the subsitution. The representation was fairly compact, but relied
/// on string manipulation with structural information limited to indexes and
/// extents.
/// 
class QueryTemplate {
public:
    /// An abstract entry in a query template
    class Entry {
    public:
        virtual ~Entry() {}
        virtual std::string getValue() const = 0;
        /// isDynamic signals whether the entry is concrete or substitutable.
        virtual bool isDynamic() const { return false; }
    };
    class StringEntry : public Entry {
    public:
        StringEntry(std::string const& s_) : s(s_) {}
        virtual std::string getValue() const { return s; } 
        std::string s;
    };
    /// An abstract mapping from entry to entry
    class EntryMapping {
    public:
        virtual ~EntryMapping() {}
        virtual boost::shared_ptr<Entry> mapEntry(Entry const& e) const = 0;
    };

    QueryTemplate() {}

    void append(std::string const& s);
    void append(ColumnRef const& cr);
    void append(TableRefN const& tr);
    void append(boost::shared_ptr<Entry> const& e);

    std::string dbgStr() const;
    std::string generate() const;
    std::string generate(EntryMapping const& em) const;
    void clear();
    void optimize();

private:
    std::list<boost::shared_ptr<Entry> > _entries;
};
typedef std::list<boost::shared_ptr<QueryTemplate> >QueryTemplateList;

}}} // lsst::qserv::master
#endif // LSST_QSERV_MASTER_QUERYTEMPLATE_H
