x-worker-mariadb:
    &worker-mariadb
    image: "${QSERV_MARIADB_IMAGE:?err}"
    init: true
    command: --port 3306
    environment:
        MYSQL_ROOT_PASSWORD: CHANGEME
x-worker-mariadb-cnf-volume:
    &worker-mariadb-cnf-volume
    - type: bind
      source: ../../src/admin/templates/mariadb/etc/my.cnf
      target: /etc/mysql/my.cnf
x-log-volume:
    &log-volume
    - type: bind
      source: ./log/
      target: /config-etc/log/
x-worker-svc:
    &worker-svc
    image: "${QSERV_IMAGE:?err}"
    init: true
    expose:
        - "3306" # for the worker db, which shares this container's network stack.
x-repl-worker:
    &repl-worker
    image: "${QSERV_IMAGE:?err}"
    init: true
    expose:
        - "25000"
        - "25001"
        - "25002"
        - "25003"
        - "25004"

volumes:
    volume_czar_xrootd:
    volume_czar_home:
    volume_czar_cfg:
    volume_czar_transfer:

    volume_czar_mariadb_data:
    volume_czar_mariadb_cfg:
    volume_czar_mariadb_home:
    volume_czar_mariadb_lib:
    volume_czar_mariadb_log:
    volume_czar_mariadb_run:

    volume_worker_0_data:
    volume_worker_0_results:
    volume_worker_0_home:
    volume_worker_0_mariadb_lib:
    volume_worker_0_mariadb_run:

    volume_worker_1_data:
    volume_worker_1_results:
    volume_worker_1_home:
    volume_worker_1_mariadb_lib:
    volume_worker_1_mariadb_run:

    volume_repl_mariadb_data:
    volume_repl_mariadb_home:
    volume_repl_mariadb_lib:

    volume_repl_worker_0_cfg:
    volume_repl_worker_1_cfg:

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 192.168.3.0/24

services:
    # worker 0 uses and validates ip+port to connect to the worker-mariadb
    worker-mariadb-0:
        << : *worker-mariadb
        volumes:
            - << : *worker-mariadb-cnf-volume
            - type: volume
              source: volume_worker_0_data
              target: /qserv/data
            - type: volume
              source: volume_worker_0_results
              target: /qserv/data/results
            - type: volume
              source: volume_worker_0_mariadb_lib
              target: /var/lib/mysql
            - type: volume
              source: volume_worker_0_mariadb_run
              target: /var/run/mysqld  # This is where the mariadb container puts the socket file
        network_mode: "service:worker-svc-0"

    worker-svc-0:
        << : *worker-svc
        command: >
          entrypoint worker-svc
          --db-uri mysql://qsmaster:CHANGEME@127.0.0.1:3306
          --db-admin-uri mysql://root:CHANGEME@127.0.0.1:3306
          --repl-instance-id qserv_proj
          --repl-auth-key replauthkey
          --repl-admin-auth-key=repladminauthkey
          --repl-registry-host repl-registry
          --repl-registry-port 25082
          --results-dirname /qserv/data/results
          --log-cfg-file=/config-etc/log/log-worker-svc.cnf
        volumes:
            - type: volume
              source: volume_worker_0_results
              target: /qserv/data/results
            - type: volume
              source: volume_worker_0_home
              target: /home/qserv
            - type: volume
              source: volume_worker_0_mariadb_run
              target: /qserv/mariadb/run  # This matches the ?socket=... location in --db-uri and --db-admin-uri
            - << : *log-volume
        networks:
            default:
                aliases:
                    - worker-mariadb-0
    repl-worker-0:
        << : *repl-worker
        command: >
          entrypoint worker-repl
          --db-admin-uri mysql://root:CHANGEME@worker-mariadb-0:3306/qservw_worker
          --repl-connection mysql://qsreplica@repl-mariadb:3306/qservReplica
          --log-cfg-file=/config-etc/log/log-repl-worker.cnf
          --
          --instance-id=qserv_proj
          --auth-key=replauthkey
          --admin-auth-key=repladminauthkey
          --registry-host=repl-registry
          --debug
        volumes:
            - type: volume
              source: volume_worker_0_data
              target: /qserv/data
            - type: volume
              source: volume_repl_worker_0_cfg
              target: /config-etc
            - type: volume
              source: volume_worker_0_home
              target: /home/qserv
            - << : *log-volume

    # worker 1 uses and validates socket file (where possible) to connect to the worker-mariadb
    worker-mariadb-1:
        << : *worker-mariadb
        volumes:
            - << : *worker-mariadb-cnf-volume
            - type: volume
              source: volume_worker_1_data
              target: /qserv/data
            - type: volume
              source: volume_worker_1_results
              target: /qserv/data/results
            - type: volume
              source: volume_worker_1_mariadb_lib
              target: /var/lib/mysql
            - type: volume
              source: volume_worker_1_mariadb_run
              target: /var/run/mysqld  # This is where the mariadb container puts the socket file
        network_mode: "service:worker-svc-1"

    worker-svc-1:
        << : *worker-svc
        command: >
          entrypoint --log-level DEBUG worker-svc
          --db-uri mysql://qsmaster:CHANGEME@127.0.0.1:3306?socket={{db_socket}}
          --db-admin-uri mysql://root:CHANGEME@127.0.0.1:3306?socket={{db_socket}}
          --repl-instance-id qserv_proj
          --repl-auth-key replauthkey
          --repl-admin-auth-key=repladminauthkey
          --repl-registry-host repl-registry
          --repl-registry-port 25082
          --results-dirname /qserv/data/results
          --targs db_socket=/qserv/mariadb/run/mysqld.sock
          --log-cfg-file=/config-etc/log/log-worker-svc.cnf
        volumes:
            - type: volume
              source: volume_worker_1_results
              target: /qserv/data/results
            - type: volume
              source: volume_worker_1_home
              target: /home/qserv
            - type: volume
              source: volume_worker_1_mariadb_run
              target: /qserv/mariadb/run  # This matches the ?socket=... location in --db-uri and --db-admin-uri
            - << : *log-volume
        networks:
            default:
                aliases:
                    - worker-mariadb-1
    repl-worker-1:
        << : *repl-worker
        # qserv-replica-worker app does not support socket file yet.
        command: >
          entrypoint worker-repl
          --db-admin-uri mysql://root:CHANGEME@worker-mariadb-1:3306/qservw_worker
          --repl-connection mysql://qsreplica@repl-mariadb:3306/qservReplica
          --log-cfg-file=/config-etc/log/log-repl-worker.cnf
          --
          --instance-id=qserv_proj
          --auth-key=replauthkey
          --admin-auth-key=repladminauthkey
          --registry-host=repl-registry
          --debug
        volumes:
            - type: volume
              source: volume_worker_1_data
              target: /qserv/data
            - type: volume
              source: volume_repl_worker_1_cfg
              target: /config-etc
            - type: volume
              source: volume_worker_1_home
              target: /home/qserv
            - << : *log-volume

    czar-mariadb:
        image: "${QSERV_MARIADB_IMAGE:?err}"
        init: true
        command: --port 3306
        network_mode: "service:czar-proxy"
        environment:
            MYSQL_ROOT_PASSWORD: CHANGEME
        volumes:
            - type: volume
              source: volume_czar_mariadb_data
              target: /qserv/data
            - type: bind
              source: ../../src/admin/templates/mariadb/etc/my.cnf
              target: /etc/mysql/my.cnf
            - type: volume
              source: volume_czar_mariadb_lib
              target: /var/lib/mysql
            - type: volume
              source: volume_czar_mariadb_log
              target: /var/log/mysql
            - type: volume
              source: volume_czar_mariadb_run
              target: /var/run/mysqld

    czar-proxy:
        image: "${QSERV_IMAGE:?err}"
        init: true
        command: >
          entrypoint --log-level DEBUG proxy
          --db-uri mysql://qsmaster:CHANGEME@127.0.0.1:3306?socket={{db_socket}}
          --db-admin-uri mysql://root:CHANGEME@127.0.0.1:3306?socket={{db_socket}}
          --targs db_socket=/qserv/mariadb/run/mysqld.sock
          --log-cfg-file=/config-etc/log/log-czar-proxy.cnf
          --repl-instance-id qserv_proj
          --repl-auth-key replauthkey
          --repl-admin-auth-key=repladminauthkey
          --repl-registry-host repl-registry
          --repl-registry-port 25082
        volumes:
            - type: volume
              source: volume_czar_mariadb_data
              target: /qserv/data
            - type: volume
              source: volume_czar_mariadb_cfg
              target: /config-etc
            - type: volume
              source: volume_czar_mariadb_home
              target: /home/qserv
            - type: volume
              source: volume_czar_mariadb_run
              target: /qserv/mariadb/run
            - type: volume
              source: volume_czar_transfer
              target: /tmp
              
            - << : *log-volume
        expose:
            - "3306" # for czar-mariadb
            - "4040"
        networks:
            default:
                aliases:
                    - czar-mariadb
        # ports:
        #     - "127.0.0.1:4040:4040"
    czar-http:
        image: "${QSERV_IMAGE:?err}"
        init: true
        command: >
          entrypoint --log-level DEBUG czar-http
          --db-uri mysql://qsmaster:CHANGEME@czar-mariadb:3306/
          --czar-name http
          --http-port 4048
          --http-threads 4
          --http-worker-ingest-threads 2
          --http-ssl-cert-file /config-etc/ssl/czar-cert.pem
          --http-ssl-private-key-file /config-etc/ssl/czar-key.pem
          --http-tmp-dir /tmp
          --http-conn-pool-size 2
          --user qsmaster
          --password CHANGEME
          --log-cfg-file=/config-etc/log/log-czar-proxy.cnf
          --repl-instance-id qserv_proj
          --repl-auth-key replauthkey
          --repl-admin-auth-key=repladminauthkey
          --repl-registry-host repl-registry
          --repl-registry-port 25082
        volumes:
            - type: volume
              source: volume_czar_cfg
              target: /config-etc
            - type: volume
              source: volume_czar_transfer
              target: /tmp
            - type: volume
              source: volume_czar_home
              target: /home/qserv
            - << : *log-volume
        expose:
            - "4048"
        ports:
            - "0.0.0.0:${QSERV_HTTP_FRONTEND_PORT:-4048}:4048"
    repl-mariadb:
        image: "${QSERV_MARIADB_IMAGE:?err}"
        init: true
        command: --port 3306
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: CHANGEME
        volumes:
            - type: volume
              source: volume_repl_mariadb_data
              target: /qserv/data
            - type: bind
              source: ../../src/admin/templates/repl-db/etc/my.cnf
              target: /etc/mysql/my.cnf
            - type: volume
              source: volume_repl_mariadb_lib
              target: /var/lib/mysql
    repl-controller:
        image: "${QSERV_IMAGE:?err}"
        init: true
        command: >
          entrypoint --log-level DEBUG replication-controller
          --db-uri mysql://qsreplica@repl-mariadb:3306/qservReplica
          --db-admin-uri mysql://root:CHANGEME@repl-mariadb:3306/qservReplica
          --qserv-czar-db=mysql://root:CHANGEME@czar-mariadb:3306/qservMeta
          --log-cfg-file=/config-etc/log/log-repl-controller.cnf
          --
          --instance-id=qserv_proj
          --auth-key=replauthkey
          --admin-auth-key=repladminauthkey
          --registry-host=repl-registry
          --controller-auto-register-workers=1
          --qserv-sync-force
          --qserv-chunk-map-update
          --debug
        expose:
            - "25081"
        ports:
            - "0.0.0.0:${QSERV_DASHBOARD_PORT:-25081}:25081"
        volumes:
            - type: volume
              source: volume_repl_mariadb_data
              target: /qserv/data
            - type: volume
              source: volume_repl_mariadb_home
              target: /home/qserv
            - type: bind
              source: ../../src/www
              target: /usr/local/qserv/www
            - << : *log-volume
    repl-registry:
        image: "${QSERV_IMAGE:?err}"
        init: true
        command: >
          entrypoint --log-level DEBUG replication-registry
          --db-uri mysql://qsreplica@repl-mariadb:3306/qservReplica
          --db-admin-uri mysql://root:CHANGEME@repl-mariadb:3306/qservReplica
          --log-cfg-file=/config-etc/log/log-repl-registry.cnf
          --
          --instance-id=qserv_proj
          --auth-key=replauthkey
          --admin-auth-key=repladminauthkey
          --debug
        expose:
            - "25082"
        volumes:
            - << : *log-volume
