/*
 * LSST Data Management System
 *
 * This product includes software developed by the
 * LSST Project (http://www.lsst.org/).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the LSST License Statement and
 * the GNU General Public License along with this program.  If not,
 * see <http://www.lsstcorp.org/LegalNotices/>.
 */
#ifndef LSST_QSERV_REPLICA_DATABASEMYSQLUTILS_H
#define LSST_QSERV_REPLICA_DATABASEMYSQLUTILS_H

// System headers
#include <functional>
#include <memory>
#include <string>

// Third-party headers
#include "nlohmann/json.hpp"

// Qserv headers
#include "replica/mysql/DatabaseMySQLRow.h"
#include "replica/util/Common.h"

// Forward declarations
namespace lsst::qserv::replica::database::mysql {
class Connection;
class Warning;
}  // namespace lsst::qserv::replica::database::mysql

// This header declarations
namespace lsst::qserv::replica::database::mysql {

namespace detail {
bool selectSingleValueImpl(std::shared_ptr<Connection> const& conn, std::string const& query,
                           std::function<bool(Row&)> const& onEachRow, bool noMoreThanOne = true);
}  // namespace detail

/**
 * The convenience method for executing queries from which a single value
 * would be extracted.
 *
 * @note By default, the method requires a result set to have 0 or 1 rows.
 *   Otherwise an exception be thrown. This requirement can be relaxed by setting
 *   a value of the optional parameter noMoreThanOne=false. In that case a value
 *   of the very first row will be extracted.
 *
 * @param conn The MySQL connection that was used to execute the last statement.
 * @param query A query to be executed.
 * @param val A value to be set (unless the field contains NULL).
 * @param colIdx The optional zero-based index of a column from which to extract a value.
 * @param noMoreThanOne A flag (if set) alowing more than one row in the result set.
 *
 * @return 'true' if the value is not NULL.
 *
 * @throws logic_error If the query is not supposed to return any result set,
 *   or if the result set has nore than 1 row (unless noMoreThanOne = false).
 * @throws EmptyResultSetError If a result set is empty.
 * @throws InvalidTypeError If the conversion to a proposed type will fail.
 */
template <typename T>
inline bool selectSingleValue(std::shared_ptr<Connection> const& conn, std::string const& query, T& val,
                              size_t colIdx = 0, bool noMoreThanOne = true) {
    auto const onEachRow = [&](Row& row) -> bool { return row.get(colIdx, val); };
    return detail::selectSingleValueImpl(conn, query, onEachRow, noMoreThanOne);
}

/// A variant for the above-defined single value selector based on the name of a column.
template <typename T>
inline bool selectSingleValue(std::shared_ptr<Connection> const& conn, std::string const& query, T& val,
                              std::string const& colName, bool noMoreThanOne = true) {
    auto const onEachRow = [&](Row& row) -> bool { return row.get(colName, val); };
    return detail::selectSingleValueImpl(conn, query, onEachRow, noMoreThanOne);
}

/**
 * Report info on the on-going queries using 'SHOW [FULL] PROCESSLIST'.
 * @param A scope of the operaton depends on the user credentials privided
 *   in the configuration object. Normally, a subset of queries which belong
 *   to the specified user will be reported.
 * @param conn The MySQL connection for executing the query.
 * @param full The optional modifier which (if set) allows seeing the full text
 *   of the queries.
 * @return A collection of queries encoded as the JSON object. Please, see the code
 *   for further details on the schema of the object.
 * @throws mysql::Error on errors detected during query execution/processing.
 */
nlohmann::json processList(std::shared_ptr<Connection> const& conn, bool full = false);

/**
 * The utility functions obj2fs and fs2obj convert between object names (such as database or
 * table names) and the corresponding file system-safe names generated by MySQL.
 * Function isValidObjectName checks if the object name is valid.
 * @see https://dev.mysql.com/doc/refman/8.4/en/identifier-mapping.html
 * @note The current implementation of all 3 functions presently supports translation
 *  of the printable 7-bit ASCII characters only. Symbols like NUL, CR, LF, and other
 *  non-printable characters are not supported. Full support for the UTF-8 characters
 * is not implemented yet.
 */

/**
 * Translate the object name into the file system name.
 * @param objectName The name of an object to be converted.
 * @return The file system-safe name of the object.
 * @throws std::invalid_argument If the object name is empty.
 */
std::string obj2fs(std::string const& objectName);

/**
 * Translate the filesystem name into the object name.
 * @param fileSystemName The file system-safe name of an object to be converted.
 * @return The object name.
 * @throws std::invalid_argument If the file system name is empty.
 */
std::string fs2obj(std::string const& fileSystemName);

/**
 * Check if the object name is valid (i.e. it doesn't contain any characters
 * that can't be translated into the file system-safe name by the current
 * implementation).
 * @param objectName The name of an object to be checked.
 * @return 'true' if the name is valid, 'false' otherwise.
 * @throws std::invalid_argument If the object name is empty.
 */
bool isValidObjectName(std::string const& objectName);

/**
 * Extract the table schema from the information schema of the MySQL database.
 * @param conn The MySQL connection for executing the query.
 * @param databaseName The name of a database.
 * @param tableName The name of a table.
 * @return The JSON array with the following schema:
 * @code
 *  [
 *    {"ORDINAL_POSITION":         <number>,
 *     "COLUMN_NAME":              <string>,
 *     "COLUMN_TYPE":              <string>,
 *     "DATA_TYPE":                <string>,
 *     "NUMERIC_PRECISION":        <string>|"",
 *     "CHARACTER_MAXIMUM_LENGTH": <string>|"",
 *     "IS_NULLABLE":              {"YES"|"NO"},
 *     "COLUMN_DEFAULT":           <string>|"",
 *     "COLUMN_COMMENT":           <string>|"",
 *     "IS_GENERATED":             {"ALWAYS"|"NEVER"},
 *     "GENERATION_EXPRESSION":    <string>|"">
 *     "EXTRA":                    <string>|""
 *    },
 *    ...
 *  ]
 * @endcode
 * @note
 * - All but the "ORDINAL_POSITION" field are strings, including those which are numeric.
 * - The numeric fields "NUMERIC_PRECISION", "CHARACTER_MAXIMUM_LENGTH"
 *   and "COLUMN_DEFAULT" (for numeric columns) are converted to strings for
 *   the sake of uniformity.
 * - The NULL values are converted into empty strings.
 * - The "ORDINAL_POSITION" field is 1-based.
 * - The "IS_NULLABLE" field is either "YES" or "NO".
 * - The "EXTRA" field contains additional information about the column, such as
 *   "AUTO_INCREMENT", etc.
 * - The rows are sorted by the "ORDINAL_POSITION" field in ascending order.
 * @throws std::invalid_argument If the connectin pointer, or the database or the table name is empty.
 * @throws mysql::Error on errors detected during query execution/processing.
 */
nlohmann::json tableSchemaDetailed(std::shared_ptr<Connection> const& conn, std::string const& databaseName,
                                   std::string const& tableName);

/**
 * Extract the table schema from the information schema of the MySQL database and return
 * it in the format suitable for the CREATE TABLE statement. Otherwise the method is the same as
 * tableSchemaDetailed.
 *
 * The implementation of the generator is based on the syntax of the table creation
 * command in the MySQL documentation:
 * https://dev.mysql.com/doc/refman/8.4/en/create-table.html
 *
 * @param conn The MySQL connection for executing the query.
 * @param databaseName The name of a database.
 * @param tableName The name of a table.
 * @param columnsToExclude The optional set of column names to be excluded from
 *   the resulting schema.
 * @return The JSON array with the following schema:
 * @code
 *  [
 *    {"name": <string>, "type": <string>},
 *    ...
 *  ]
 * @endcode
 * For example:
 * @code
 *  [
 *    {"name": "id", "type": "INT NOT NULL AUTO_INCREMENT"},
 *    {"name": "name", "type": "VARCHAR(255) NOT NULL"},
 *    {"name": "value", "type": "DOUBLE DEFAULT NULL"},
 *    {"name": "mag", "type": "FLOAT GENERATED ALWAYS AS (scisql_nanojanskyToAbMag(`flux`)) VIRTUAL"},
 *    ...
 *  ]
 * @endcode
 * @note
 * - The "name" field is the name of a column.
 * - The "type" field is the column type as it should be used in the CREATE TABLE statement.
 * - The data type part of the "type" field is in upper case (e.g. 'INT', 'INT UNSIGNED'. 'VARCHAR', etc).
 * - The rows are sorted by the "ORDINAL_POSITION" field in ascending order.
 * @throws std::invalid_argument If the connectin pointer, or the database or the table name is empty.
 * @throws mysql::Error on errors detected during query execution/processing.
 */
nlohmann::json tableSchemaForCreate(std::shared_ptr<Connection> const& conn, std::string const& databaseName,
                                    std::string const& tableName,
                                    std::set<std::string> const& columnsToExclude = {});

}  // namespace lsst::qserv::replica::database::mysql

#endif  // LSST_QSERV_REPLICA_DATABASEMYSQLUTILS_H
