#!/usr/bin/perl -w

use strict;
use Getopt::Long;

Getopt::Long::config('bundling_override');
my %opts = ();
GetOptions( \%opts, 
	"debug",
	"help|h",
	"set",
	"status|s",
	"stripes=i",
	"stop",
	"start",
	"substripes=i",
	"load",
	"source=s",
	"table=s",
	"output=s",
	"partition",
	"test"
);
usage(1) if ($Getopt::Long::error); 
usage(0) if ($opts{'help'});

my $debug = $opts{'debug'} || 0;

my $install_dir = "INSTALLDIR";

#mysql variables
my $mysqld_sock = "$install_dir/var/lib/mysql/mysql.sock";

if( $opts{'status'} ) {
	if( check_mysqld() ) {
		print "Mysql server up and running.\n";
	} else {
		print "Mysql server not running.\n";
	}

	if( check_proxy() ) {
		print "Mysql proxy up and running.\n";
	} else {
		print "Mysql proxy not running.\n";
	}

	if( check_xrootd() ) {
		print "Xrootd server up and running.\n";
	} else {
		print "Xrootd server not running.\n";
	}

	if( check_qserv() ) {
		print "Qserv server up and running.\n";
	} else {
		print "Qserv server not running.\n";
	}

} elsif( $opts{'stop'} ) {
	
	print "Stopping mysql-proxy\n";
	stop_proxy();
	print "Stopping xrootd\n";
	stop_xrootd();
	print "Stopping mysqld\n"; 
	stop_mysqld();
	print "Stopping qserv\n"; 
	stop_qserv();
	
} elsif( $opts{'start'} ) {

	start_proxy();
	start_xrootd();
	start_mysqld();
	start_qserv();
	
} elsif( $opts{'partition'} ) {

	#need to partition raw data for loading into qserv.
	unless( $opts{'source'} ) {
		print "Error: you need to set the path to the source data with the --source option.\n";
		exit(1);
	}
	unless( $opts{'table'} ) {
		print "Error: you need to specify the table name for the source data with the --table option.\n";
		exit(1);
	}
	unless( $opts{'output'} ) {
		print "Error: you need to specify the output path with the --output option.\n";
		exit(1);
	}
	
	partition_data( $opts{'source'}, $opts{'output'}, $opts{'table'} );
	
} elsif( $opts{'load'} ) {

        #need to partition raw data for loading into qserv.
        unless( $opts{'source'} ) {
                print "Error: you need to set the path to the source data with the --source option.\n";
               	exit(1);
        }
        unless( $opts{'table'} ) {
                print "Error: you need to specify the table name for the source data with the --table option.\n";
               	exit(1);
        }
       	unless( $opts{'output'} ) {
                print "Error: you need to specify the output path with the --output option.\n";
                exit(1);
        }

	#need to load data into qserv
	load_data( $opts{'source'}, $opts{'output'}, $opts{'table'} );
} elsif( $opts{'set'} ) {

	unless( $opts{'stripes'} && $opts{'stripes'} =~ /\d+/ ) {
		print "Error: sorry you need to set the stripes you are using with the 'stripes' option\n";
		exit(1);
	}
	unless( $opts{'substripes'} && $opts{'substripes'} =~ /\d+/ ) {
		print "Error: sorry you need to set the substripes you are using with the 'substripes' option\n";
		exit(1);
	}
	
	set_stripes( $opts{'stripes'}, $opts{'substripes'} );
}

exit( 0 );

#############################################################

#Check the sql server status, if it is up or down by using 
#an sql command for input.
sub check_sql_server {
	my( $command ) = @_;

	print "Testing sql with command $command\n" if( $debug );
	
	my $testsql = "/tmp/tmp.sql";
	create_test_sql( $testsql );
	
	#try through the proxy to see if it can talk to mysql server.
	my @reply = `$command < $testsql 2>&1`;
	
	print "@reply\n" if( $debug );
	
	if( $reply[0] =~ /Database/ ) {
		return 1;
	} else {
		return 0;
	}
	
	unlink "$testsql";
	
}

#Create a test sql command to test the sql server.
sub create_test_sql {
	my( $testsql ) = @_;
	
	#create tmp sql file
	open TMPFILE, ">$testsql";
	print TMPFILE "show databases;\n";
	close TMPFILE;
	
}

#check the mysql proxy use.
sub check_proxy {

	return check_sql_server( "mysql --port=4040 --protocol=TCP" );

}

#check the mysql server status.
sub check_mysqld {

	if( -e "$mysqld_sock" ) {
		return check_sql_server( "mysql -S $mysqld_sock -u root" );
	} else {
		return 0;
	}
}

#check the xrootd process.
sub check_xrootd {
	
	if( check_ps( "xrootd -c" ) && check_ps( "cmsd -c" ) ) {
		return 1;
	} else {
		return 0;
	}

}

#check the qserv process.
sub check_qserv {
	
	return check_ps( "startQserv" );

}

#Check the existence of a process in the process table by a test 
#string in the command line used.
sub check_ps {
	my( $test_string ) = @_;
	#print "$test_string\n";
	
	my @reply = `ps x`;
	#print @reply;
	my @stuff = grep /$test_string/, @reply;
	#print @stuff;
	
	if( @stuff ) {
		my( $pid ) = $stuff[0] =~ /^\s*(\d+) /;
		return $pid;
	} else {
		return 0;
	}
}

#Stop the qserv process
sub stop_qserv {

	stop_ps( "startQserv" );

}

#stop the xrootd process
sub stop_xrootd {

	stop_ps( "xrootd -c" );
	stop_ps( "cmsd -c" );

}

#stop the mysql server
sub stop_mysqld {

	stop_ps( "mysqld --basedir" );

}

#stop the mysql proxy
sub stop_proxy {

	stop_ps( "mysql-proxy" );

}


#Stop a process based on the exsitence of a string in the command line
#used to start the process.
sub stop_ps {
	my( $test_string ) = @_;
	#print "$test_string\n";
	
	my $pid = check_ps( $test_string );
	#print "pid to stop -- $pid\n";
	if( $pid ) {
		if( $opts{'test'} ) {
			print "I would now kill process $pid.\n";
		} else {
			`kill $pid`;
		}
	}

}

sub start_proxy {

	system("$install_dir/start_mysqlproxy");

}

sub start_mysqld {

	system("$install_dir/bin/mysqld_safe &");

}

sub start_qserv {

	system("$install_dir/start_qserv");

}

sub start_xrootd {

	system("$install_dir/start_xrootd");
	
}

sub set_stripes {
	my( $stripes, $substripes ) = @_;
	
	my $reply = `grep stripes $install_dir/etc/local.qserv.cnf`;
	
	if( $reply =~ /stripes\s*=\s*\d+/ ) {
		print "Error: sorry, you have already set the stripes to use for the data.\n";
		print "    please edit the local.qserv.cnf and remove the stripes value if you really want to change this.\n";
		return;
	}

	`perl -pi -e 's,^substripes\\s*=,substripes = $substripes,' $install_dir/etc/local.qserv.cnf`;
	`perl -pi -e 's,^stripes\\s*=,stripes = $stripes,' $install_dir/etc/local.qserv.cnf`;

}

#Partition the pt11 example data for use into chunks.  This is the example
#use of partitioning, and this should be more flexible to create different
#amounts of chunks, but works for now.
sub partition_data {
	my( $source_dir, $output_dir, $tablename ) = @_;
	
	my $stripes;
	my $substripes;
	
	my $reply = `grep stripes $install_dir/etc/local.qserv.cnf`;
	if( $reply =~ /^stripes\s*=\s*(\d+)/ ) {
		if( $opts{'stripes'} ) {
			unless( $opts{'stripes'} == $1 ) {
				print "Warning: you used $1 for stipes before.  Please check which stripes value you wish to use.\n";
				return;
			}
		}
		$stripes = $1;
	} else {
		if( $opts{'stripes'} ) {
			$stripes = $opts{'stripes'};
		} else {
			print "Error: sorry you need to set the stripes value before partitioning.\n";
			return;
		}
	}
	
	$reply = `grep substripes $install_dir/etc/local.qserv.cnf`;
	if( $reply =~ /substripes\s*=\s*(\d+)/ ) {
		if( $opts{'substripes'} ) {
			unless( $opts{'substripes'} == $1 ) {
				print "Warning: you used $1 for substipes before.  Please check which substripes value you wish to use.\n";
				return;
			}
		}
		$stripes = $1;
	} else {
		if( $opts{'substripes'} ) {
			$stripes = $opts{'substripes'};
		} else {
			print "Error: sorry you need to set the substripes value before partitioning.\n";
			return;
		}
	}
	
	my( $dataname ) = $source_dir =~ m!/([^/]+)$!;
	
	if( -d "$output_dir" ) {
		chdir "$output_dir";
	} else {
		print "Error: the output dir $output_dir doesn't exist.\n";
	}

	#need to have the various steps to partition data
	my $command = "$install_dir/bin/python $install_dir/qserv/master/examples/partition.py ".
		"-P$tablename -t 2 -p 4 $source_dir/${tablename}.txt -S $stripes -s $substripes";
	if( $opts{'test'} ) {
		print "$command\n";
	} else {
		`$command`;
	}
}

#load the partitioned pt11 data into qserv for use.  This does a number of
#steps all in one command.
sub load_data {
	my( $source_dir, $location, $tablename ) = @_;
	
	#check the stripes value
	my $stripes = get_value( 'stripes' );
	
	unless( $stripes ) {
		print "Error: sorry, the stripes value is unknown, please set it with the 'set' option.\n";
		return;
	}
	
	#create database if it doesn't exist
	`$install_dir/bin/mysql -S $install_dir/var/lib/mysql/mysql.sock -u root -e 'Create database if not exists LSST;'`;
	
	#check on the table def, and add need columns
	print "Copy and changing $source_dir/${tablename}.sql\n";
	my $tmptable = lc $tablename;
	`cp $source_dir/${tablename}.sql $install_dir/tmp`;
	`perl -pi -e 's,^.*_chunkId.*\n,,' $install_dir/tmp/${tablename}.sql`;
	`perl -pi -e 's,^.*_subChunkId.*\n,,' $install_dir/tmp/${tablename}.sql`;
	`perl -pi -e 's!^\(\\s*PRIMARY\)!  chunkId int\(11\) default NULL,\\n\\1!' $install_dir/tmp/${tablename}.sql`;
	`perl -pi -e 's!^\(\\s*PRIMARY\)!  subChunkId int\(11\) default NULL,\\n\\1!' $install_dir/tmp/${tablename}.sql`;

	open TMPFILE, ">>$install_dir/tmp/${tablename}.sql";
	print TMPFILE "\nCREATE INDEX obj_subchunk_idx on Object ( subChunkId );\n";
	close TMPFILE;

	#regress through looking for partitioned data, create loading script
	open LOAD, ">$install_dir/tmp/${tablename}_load.sql";
	
	my %chunkslist = ();
	opendir DIR, "$location";
	my @dirslist = readdir DIR;
	closedir DIR;
	
	#look for paritioned table chunks, and create the load data sqls.
	foreach my $dir ( sort @dirslist ) {
		next if( $dir =~ /^\./ );
		
		if( $dir =~ /^stripe/ ) {
			opendir DIR, "$location/$dir";
			my @filelist = readdir DIR;
			closedir DIR;
			
			foreach my $file ( sort @filelist ) {
				if( $file =~ /(\w+)_(\d+).csv/ ) {
					my $loadname = "${1}_$2";
					if( $1 eq $tablename ) {
					print LOAD "CREATE TABLE IF NOT EXISTS $loadname LIKE $tablename;\n";
					print LOAD "LOAD DATA INFILE '$location/$dir/$file' INTO TABLE $loadname FIELDS TERMINATED BY ',';\n";

					$chunkslist{$2} = 1;
					}
					if( $tablename eq 'Object' && $1 =~ /^Object\S+Overlap/ ) {
						print LOAD "CREATE TABLE IF NOT EXISTS $loadname LIKE $tablename;\n";
						print LOAD "LOAD DATA INFILE '$location/$dir/$file' INTO TABLE $loadname FIELDS TERMINATED BY ',';\n";
					}
				}
			}
		}
	}
	print LOAD "CREATE TABLE IF NOT EXISTS ${tablename}_1234567890 LIKE $tablename;\n";
	close LOAD;
	
	#load the data into the mysql instance
	print "Loading data, this make take awhile...\n";
	`$install_dir/bin/mysql -S $install_dir/var/lib/mysql/mysql.sock -u root LSST < $install_dir/tmp/${tablename}.sql`;
	`$install_dir/bin/mysql -S $install_dir/var/lib/mysql/mysql.sock -u root LSST < $install_dir/tmp/${tablename}_load.sql`;
		
	#create the empty chunks file
	unless( -e "$install_dir/etc/emptyChunks.txt" ) {
		create_emptychunks( $stripes, \%chunkslist );
	}
	
	#create a setup file
	unless( -e "$install_dir/etc/setup.cnf" ) {
		open SETUP, ">$install_dir/etc/setup.cnf";
		print SETUP "host:localhost\n";
		print SETUP "port:4040\n";
		print SETUP "user:root\n";
		print SETUP "pass:\n";
		print SETUP "sock:$install_dir/var/lib/mysql/mysql.sock\n";
		close SETUP;
	}

	#check if database is already registered
	unless( -e "$install_dir/xrootd-run/q/LSST" ) {
		#register the database, export
		my $command = "$install_dir/qserv/worker/tools/qsDbTool ";
		$command .= "-a $install_dir/etc/setup.cnf -i 1 ";
		$command .= "register LSST $tablename";
		print "Command: $command\n";
		`$command`;
		
		$command = "$install_dir/qserv/worker/tools/qsDbTool ";
		$command .= "-a $install_dir/etc/setup.cnf -i 1 -b $install_dir/xrootd-run ";
		$command .= "export LSST";
		print "Command: $command\n";
		`$command`;
	}

}

#Create the empty chucks list up to 1000, and print this into the
#empty chunks file in etc.
sub create_emptychunks {
	my( $stripes, $chunkslist ) = @_;
	
	my $top_chunk = 2 * $stripes * $stripes;
		
	open CHUNKS, ">$install_dir/etc/emptyChunks.txt";
	for( my $i = 0; $i < $top_chunk; $i++ ) {
		unless( defined $chunkslist->{$i} ) {
			print CHUNKS "$i\n";
		}
	}
	close CHUNKS;
	
}

#routine to get the value from the config file
sub get_value {
	my( $text ) = @_;
	
	open CNF, "<$install_dir/etc/local.qserv.cnf";
	while( my $line = <CNF> ) {
		if( $line =~ /^$text\s*=\s*(\d+)/ ) {
			close CNF;
			return $1;
		}
	}
	close CNF;
	
}

#help report for the --help option
sub usage {
  my($exit, $message) = @_;

        my($bin) = ($0 =~ m!([^/]+)$!);
        print STDERR $message if defined $message;
        print STDERR <<INLINE_LITERAL_TEXT;     
usage: $bin [options]
  Help admin the qserv server install, starting, stopping, and checking of status
  Also supports the loading of pt11 example data into the server for use.

Options are:
      --debug     Print out debug messages.
  -h, --help      Print out this help message.
      --set       Set the stripes and substripes values, needs strips and substripes options.
  -s, --status    Print out the status of the server processes.
      --stop      Stop the servers.
	  --start     Start the servers.
	  --stripes   Number of stripes used to partition the data.
	  --subtripes Numebr of substripes used to partition the data.
	  --load      Load data into qserv, requires options source, output, table
	  --source    Path to the pt11 exmple data
	  --output    Path to the paritioned data
	  --table     Table name for partitioning and loading
	  --parition  Partition the example pt11 data into chunks, requires source, output, table
	  --test      test the use of the util, without performing the actions.

Examples: $bin --status

Comments to Douglas Smith <douglas\@slac.stanford.edu>.
INLINE_LITERAL_TEXT

	       exit($exit) if defined $exit;

}
