import glob, os, re, sys
import errno
import shutil

srcDir = "python/lsst/qserv/admin"
destDir = "dist"
pList = ["lsst", "qserv", "admin"]

if not os.path.exists(destDir):
    os.mkdir(destDir)

destDirFull = destDir
for p in pList:
    destDirFull += "/%s" % p
    if not os.path.exists(destDirFull):
        os.mkdir(destDirFull)
    fName = "%s/__init__.py" % destDirFull
    open(fName, "w").close()

for f in os.listdir(srcDir):
    if f.endswith(".py"):
        shutil.copyfile(os.path.join(srcDir, f), os.path.join(destDirFull, f))

# and bring in the files we depend on from python/lsst/qserv/meta"
destDirFull = "%s/lsst/qserv/meta" % destDir
if not os.path.exists(destDirFull):
     os.mkdir(destDirFull)
fName = "%s/__init__.py" % destDirFull
open(fName, "w").close()

fList = ["db.py", "status.py", "client.py"]
for f in fList:
    srcF = os.path.join("../meta/python/lsst/qserv/meta", f)
    dstF = os.path.join(destDirFull, f)
    shutil.copyfile(srcF, dstF)
