# -*- python -*-
#
# Setup our environment
#
# Do not change these
import glob, os, re, sys

import detect_deps
env = Environment()

# Describe what your package contains here.
env.Help("""
Qserv common code
""")


# Detect protobufs
detect_deps.detectProtobufs()

#
# Build/install things
#

######################################################################
for d in Split("proto src tests doc"): 
    if os.path.isdir(d):
        try:
            SConscript(os.path.join(d, "SConscript"), 
                       exports={'env' : env})
        except Exception, e:
            print >> sys.stderr, "%s: %s" % (os.path.join(d, "SConscript"), e)
