-- MySQL Script generated by MySQL Workbench
-- 06/24/15 09:48:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema qservMeta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qservMeta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qservMeta` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `qservMeta` ;

-- -----------------------------------------------------
-- Table `QCzar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QCzar` (
  `cid` INT NOT NULL AUTO_INCREMENT COMMENT 'Czar identifier',
  `czar` CHAR(63) NOT NULL,
  `active` BIT NOT NULL COMMENT 'Set to 0 when czar disappears',
  PRIMARY KEY (`cid`),
  UNIQUE INDEX `QCzar_czar_UNIQUE` (`czar` ASC))
ENGINE = InnoDB
COMMENT = 'Table for czars, definition of every czar ever existed.';


-- -----------------------------------------------------
-- Table `QInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QInfo` (
  `qid` INT NOT NULL AUTO_INCREMENT COMMENT 'Query identifier, unique number',
  `qtype` ENUM('LONG', 'INTER') NOT NULL COMMENT 'Query type, either INTERACTIVE or LONG-RUNNING.',
  `cid` INT NOT NULL COMMENT 'ID of the \"responsible czar\" of this query',
  `user` CHAR(63) NOT NULL COMMENT 'Name (id) of the user submitting this query',
  `query` TEXT NOT NULL COMMENT 'Original query text as was submitted by client.',
  `qtemplate` TEXT NOT NULL COMMENT 'Query template, string used to build final per-chunk query.',
  `qresult` TEXT NULL COMMENT 'Aggregate query to be executed on results table, result of this query is sent back to user. If NULL then it is equivalent to SELECT *.',
  `submitted` TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP COMMENT 'Time when query was submitted (received from client)',
  `collected` TIMESTAMP NULL DEFAULT NULL COMMENT 'Time when all per-chunk results were collected into czar-side results table.',
  `completed` TIMESTAMP NULL DEFAULT NULL COMMENT 'Time when processing was completed (result sent back to user). NULL if not completed yet.',
  PRIMARY KEY (`qid`),
  INDEX `QInfo_cid_index` (`cid` ASC),
  INDEX `QInfo_completed_index` (`completed` ASC),
  CONSTRAINT `QInfo_cid`
    FOREIGN KEY (`cid`)
    REFERENCES `QCzar` (`cid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Table containing per-query information.';


-- -----------------------------------------------------
-- Table `QTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QTable` (
  `qid` INT NOT NULL COMMENT 'Query identifier, foreign key into QueryInfo table',
  `dbname` CHAR(63) NOT NULL COMMENT 'Database name',
  `tblname` CHAR(63) NOT NULL COMMENT 'Table name',
  PRIMARY KEY (`qid`, `dbname`, `tblname`),
  INDEX `QTable_TableNameIndex` (`dbname` ASC, `tblname` ASC),
  CONSTRAINT `QTable_qid`
    FOREIGN KEY (`qid`)
    REFERENCES `QInfo` (`qid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Table containg table names used by query.';


-- -----------------------------------------------------
-- Table `QWorker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QWorker` (
  `qid` INT NOT NULL COMMENT 'Query ID',
  `chunk` INT NOT NULL COMMENT 'Chunk number',
  `wxrd` CHAR(63) NULL DEFAULT NULL COMMENT 'Worker xrootd endpoint (host name/IP and port number)',
  `submitted` TIMESTAMP NULL DEFAULT NULL COMMENT 'Time when chunk query was submitted to worker',
  `completed` TIMESTAMP NULL DEFAULT NULL COMMENT 'Set to non-NULL when query result for this chunk is processed',
  PRIMARY KEY (`qid`, `chunk`),
  CONSTRAINT `QWorker_qid`
    FOREIGN KEY (`qid`)
    REFERENCES `QInfo` (`qid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Mapping of queries to workers';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
