qservImageName: ghcr.io/lsst/qserv:2026.5.1-rc1-60-g56d1cae46
mariadbImageName: ghcr.io/lsst/qserv-mariadb:2026.5.1-rc1
sslProxyImageName: qserv/mysql-proxy-ssl:latest
ingestHelperImageName: ghcr.io/lsst/qserv-build-base:2026.5.1-rc1-1-gfd3801377

czars:
  tier: [int-czar]

workers:
  replicas: 35
  tier: [int-worker]

replication:
  tier: [int-utility]

ingest:
  enable: true
  tier: [int-utility]

czarExternalService:
  enable: true
  type: LoadBalancer
  annotations:
    metallb.io/address-pool: sdf-dmz
  allocateLoadBalancerNodePorts: false
  loadBalancerIP: 134.79.23.230
  loadBalancerSourceRanges:
    - 35.232.79.62/32
    - 34.135.212.179/32
    - 35.225.239.81/32
    - 34.121.239.92/32
    - 134.79.0.0/16
    - 172.16.0.0/12
    - 172.24.49.51/32
