apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher-deployment
spec:
  selector:
    matchLabels:
      app: watcher
  replicas: 1
  template:
    metadata:
      labels:
        app: watcher
    spec:
      volumes:
        - name: slack-webhook-url
          secret:
            secretName: secret-watcher
      containers:
        - name: watcher
          image: qserv/lite-watcher:c1973a8b
          command: ["entrypoint"]
          args: ["--log-level", "DEBUG", "watcher", "--cluster-id", "prod", "--qserv", "mysql://qsmaster@qserv-czar:3306", "--notify-url-file", "/qserv/data/webhook_url", "--timeout-sec", "1800"]
          volumeMounts:
            - name: slack-webhook-url
              readOnly: true
              mountPath: "/qserv/data/"
