---

version: 1

disable_existing_loggers: False

formatters:

    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"



handlers:

    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: qserv-cmd.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8


    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: qserv-cmd-errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8


loggers:

    CSS:
        level: WARN 

    kazoo.client:
        level: WARN

    lsst.qserv:
        level: WARN

    lsst.qserv.admin.commons:
        level: WARN 

    lsst.qserv.admin.dataLoader:
        level: INFO 

    lsst.qserv.tests:
        level: INFO

    lsst.qserv.tests.sql:
        level: WARN 

    QADM:
        level: WARN


root:

    level: DEBUG 
    handlers: [console, info_file_handler, error_file_handler]

