# -*- python -*-
import distutils.sysconfig
import errno
import os
import state
Import('env')
Import('extraTgts')
#env.Tool('swig')
#env['SWIGFLAGS'] = ['-python', '-c++', '-Iinclude'],
#env.Append(CPPPATH = [distutils.sysconfig.get_python_inc()])
#env['SHLIBPREFIX'] = "" # Pushed to higher level SConscript

def _debug_dist_target():
    if state.log.verbose:
        state.log.debug("extraTgts['dist']")
        for (path,f) in extraTgts['dist']:
            state.log.debug("   path : %s, file : %s" % (path,str(f)))


# Manual dependencies for masterLib.i, because the SCons SWIG builder
# isn't knowledgeable enough to ensure their presence when using VariantDir
depends = ['control/transaction.h',
           'control/dispatcher.h',
           'css/StripingParams.h',
           'merger/TableMerger.h',
           'merger/mergeTypes.h',
           'query/Constraint.h',
           'qdisp/ChunkMeta.h',
           'qproc/ChunkSpec.h',
           'util/Substitution.h',
           'xrdc/xrdfile.h']
depends = map(lambda f: env.File("../"+f), depends)

localCpppath = env['CPPPATH']
if type(localCpppath) == type(""): localCpppath = [localCpppath]
localCpppath.append(distutils.sysconfig.get_python_inc())
swigged = env.SharedObject(source="masterLib.i",
                           SWIGFLAGS=['-python', '-c++', '-Iinclude'],
                           SWIGPATH=['..',
                                     distutils.sysconfig.get_python_inc()],
                           CPPPATH=localCpppath,
                           LDMODULEPREFIX='_', LDMODULESUFFIX = '.so'
                           )
# swigged = env.swig(source="masterLib.i",
#                    SWIGPATH=['..',
#                              distutils.sysconfig.get_python_inc()],
#                    LDMODULEPREFIX='_', LDMODULESUFFIX = '.so'
#                    )

#env.Append(SWIGPATH=['..', distutils.sysconfig.get_python_inc()])
#swigged = [env.File("masterLib.i")]

# print swigged # prints ['masterLib_wrap.os']

swigged_tgt = []
for f in swigged:
    swigged_tgt.append(env.File(f))

env.Depends(swigged_tgt, depends)

# Create entry for python file, which SCons SWIG builder ignores
pySwig = env.File('masterLib.py')
#env.Depends(pySwig, swigged[0]) # This causes a cycle (why?),
# but "scons --tree=all" shows that a sufficient dep
# is already there (on masterLib.i)
extraTgts["masterLib.py"] = pySwig

state.log.debug("extraTgts['dist'] %s" % extraTgts['dist'])

def markForInstall(env, pathList, extras):
    state.log.debug("markForInstall()")
    _debug_dist_target()
    python_libpath=os.path.join("lib","python")
    pyDir = os.path.join(python_libpath,*pathList)
    srcPyDir = os.path.join(*pathList)

    state.log.debug("pathList, %s" % pathList)
    state.log.debug("srcPyDir %s" % srcPyDir)
    # install py files
    for s in env.Glob(os.path.join(srcPyDir,"*.py")):
        extraTgts['dist'].append((pyDir, s))
        #env.Alias("install", env.Install(pyDir, s))
    _debug_dist_target()
    for s in extras:
        state.log.debug("extra %s" % s)
        extraTgts['dist'].append((pyDir, s))
    # touch init files will be done by python builder used 
    # for deploying others python/lsst/qserv package. See
    # InstallPythonModule() in main SConstruct

distTgts = swigged_tgt + [pySwig]

markForInstall(env, ["lsst","qserv","master"], distTgts)

for f in env.Glob("bin/*py"):
    extraTgts['dist'].append(('bin', f))

_debug_dist_target()

extraTgts["czarPy"] = distTgts
Return('swigged_tgt')
