# Using the Qserv development toolchain
FROM qserv/qserv:{DEPS_TAG_DEFAULT}

USER 0

RUN mkdir -p /qserv/bin /qserv/lib
RUN chown qserv /qserv/bin /qserv/lib

# Copy applications and libraries into the container at
# the destination folder
ADD bin/* /qserv/bin/
ADD lib/lib*.so* /qserv/lib/

COPY bin/lsst /home/qserv

USER 1000

ENV PATH=/home/qserv:$PATH
CMD ["lsst"]
