# -*- python -*-
Import('env')
import os, fnmatch
import detect_deps

# This seems not to work if placed in lib/
# The path to ../src seems to prevent scons from building .os files in
# the build dir.
sources=[]
#print os.getcwd(), os.listdir('../src')
for root, dirs, files in os.walk('../src'):
    sources += fnmatch.filter(files, "*.cc")
    # Filter out dotfiles?
    dirs = [d for d in dirs if not fnmatch.fnmatch(d, ".*")]

# Files in ../include are install targets right now. Should we change?
#env.Append(CPPPATH = ['../include']) 

e = detect_deps.checkMySql(env, Configure)
if not e:
    print "*** Cannot build ***"
    Exit(1)

lib = env.Library("qserv_common", sources)
installedLib = env.Install('../lib', lib)
env.Append(built_libs=[installedLib])
env.Install('../include/lsst/qserv', 'QservPath.hh')
env.Install('../include/lsst/qserv', 'SqlConnection.hh')
env.Install('../include/lsst/qserv', 'SqlErrorObject.hh')
