name: "Documentation"

on:
  push:

jobs:
  doc:
    name: Generate and upload documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install \
            documenteer \
            ltd-conveyor \
            sphinx-rtd-theme

      - name: Install Cmake
        run: sudo apt-get install -y cmake

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Check links
        run: |
          make docs-linkcheck

      - name: Build docs
        run: |
          make docs-html

      - name: Upload docs
        env:
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
        run: ltd upload --product qserv --gh --dir build/doc/html
