name: "Documentation"

on:
  push:

jobs:
  doc:
    name: Generate and upload documentation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: doc

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install ltd-conveyor

      - name: Check links
        run: |
          make linkcheck

      - name: Build docs
        run: |
          make html

      - name: Upload docs
        env:
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
        run: ltd upload --product qserv --gh --dir _build/html
